// Generates the compiler's diagnostic-code enum from spec/README.md.
// Parse ownership comes from parse-phase conformance cases; boundary failures
// are runtime diagnostics; all other compile-time diagnostics belong to type.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { knownCodes } from "./spec-prose.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..", "..");
const README = resolve(REPO_ROOT, "spec", "README.md");
const CASES = resolve(REPO_ROOT, "spec", "conformance", "cases.tsv");
export const OUTPUT = resolve(REPO_ROOT, "compiler", "crates", "hd_diag", "src", "codes.rs");

type Phase = "Parse" | "Type" | "Runtime";

const pascal = (code: string): string =>
  code
    .split("-")
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");

function parseCodes(cases: string): Set<string> {
  const lines = cases.trimEnd().split("\n");
  const header = lines.shift()?.split("\t") ?? [];
  const phaseAt = header.indexOf("phase");
  const expectationAt = header.indexOf("expectation");
  if (phaseAt < 0 || expectationAt < 0) throw new Error("cases.tsv lacks phase or expectation");
  const result = new Set<string>();
  for (const line of lines) {
    const fields = line.split("\t");
    const match = /^(?:reject|warn):(.*)$/.exec(fields[expectationAt] ?? "");
    if (fields[phaseAt] === "parse" && match) result.add(match[1]!);
  }
  return result;
}

function boundaryCodes(readme: string): Set<string> {
  const result = new Set<string>();
  for (const line of readme.split("\n")) {
    const row = /^\| Boundary failure \| (.*) \|$/.exec(line);
    if (row) for (const match of row[1]!.matchAll(/`([a-z0-9-]+)`/g)) result.add(match[1]!);
  }
  return result;
}

export function generateDiagnosticCodes(readme: string, cases: string): string {
  const codes = [...knownCodes(readme, "")].sort();
  const parse = parseCodes(cases);
  const runtime = boundaryCodes(readme);
  const phase = (code: string): Phase =>
    parse.has(code) ? "Parse" : runtime.has(code) ? "Runtime" : "Type";
  const variants = codes.map((code) => `    ${pascal(code)},`);
  const asStr = codes.map((code) => `            Self::${pascal(code)} => "${code}",`);
  const fromStr = codes.map((code) => `            "${code}" => Self::${pascal(code)},`);
  const phases = codes.map((code) => `            Self::${pascal(code)} => Phase::${phase(code)},`);
  return `// @generated by spec/tools/diagnostic-codes.ts; do not edit by hand.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Phase {
    Parse,
    Type,
    Runtime,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Code {
${variants.join("\n")}
    /// Internal: a stage this build needs answered \"not implemented\".
    Unsupported,
}

impl Code {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
${asStr.join("\n")}
            Self::Unsupported => "unsupported",
        }
    }

    #[must_use]
    pub fn from_str(name: &str) -> Option<Self> {
        Some(match name {
${fromStr.join("\n")}
            "unsupported" => Self::Unsupported,
            _ => return None,
        })
    }

    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {
        Self::from_str(name)
    }

    #[must_use]
    pub const fn phase(self) -> Phase {
        match self {
${phases.join("\n")}
            Self::Unsupported => Phase::Type,
        }
    }
}
`;
}

function main(args: readonly string[]): number {
  const expected = generateDiagnosticCodes(
    readFileSync(README, "utf8"),
    readFileSync(CASES, "utf8"),
  );
  if (args.length === 0) {
    writeFileSync(OUTPUT, expected);
    return 0;
  }
  if (args.length === 1 && args[0] === "--check") {
    let actual = "";
    try {
      actual = readFileSync(OUTPUT, "utf8");
    } catch {}
    if (actual === expected) return 0;
    console.error("generated diagnostic codes are stale; run spec/tools/diagnostic-codes.ts");
    return 1;
  }
  console.error("usage: diagnostic-codes.ts [--check]");
  return 2;
}

if (resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url))
  process.exitCode = main(process.argv.slice(2));
