;; commit bd985d7; command: erasure-excerpts.ts (emitWat of audit/probes/arch/alloc/alloc-loops.hd); date: 2026-09-25T20:54:17.628Z
(rec
    (type $sig0 (func (param anyref) (param i32) (result (ref null $hd.vector))))
    (type $sig1 (func (param anyref) (param i32) (result i32)))
    (type $sig2 (func (param anyref) (param i32) (result (ref null $hd.suspension))))
    (type $sig3 (func (param anyref) (param externref) (result i32)))
    (type $sig4 (func (param anyref) (param i32) (param externref) (result i32)))
    (type $sig5 (func (param anyref) (result i32)))
    (type $sig6 (func (param anyref) (param (ref null $d0)) (result i32)))
    (type $tsig0_0 (func (param anyref) (param anyref) (result i32)))
    (type $tsig1_0 (func (param anyref) (param anyref) (result i32)))
    (type $tsig2_0 (func (param anyref) (param anyref) (result i32)))
    (type $tsig3_0 (func (param anyref) (param anyref) (result (ref null $hd.bytes))))
    (type $tsig4_0 (func (param anyref) (param anyref) (param anyref) (result i32)))
    (type $tsig5_0 (func (param anyref) (param anyref) (param anyref) (result (ref null $hd.variant))))
    (type $tsig6_0 (func (param anyref) (param anyref)))
    (type $tsig7_0 (func (param anyref) (param anyref) (result (ref null $hd.variant))))
    (type $hd.suspension-poll-sig (func (param anyref) (result i32)))
    (type $hd.suspension-cancel-sig (func (param anyref)))
    (type $hd.suspension-result-sig (func (param anyref) (result anyref)))
    (type $hd.suspension (struct
      (field $hd.suspension-inner anyref)
      (field $hd.suspension-poll (ref $hd.suspension-poll-sig))
      (field $hd.suspension-cancel (ref $hd.suspension-cancel-sig))
      (field $hd.suspension-result (ref $hd.suspension-result-sig))))
    (type $hd.bytes (array (mut i8)))
    (type $hd.list (array (mut anyref)))
    (type $hd.vector (struct
      (field $hd.vector-size (mut i32))
      (field $hd.vector-values (mut (ref $hd.list)))
      (field $hd.vector-version (mut i32))))
    (type $hd.iterator (struct
      (field $hd.iterator-list (ref null $hd.vector))
      (field $hd.iterator-map (ref null $hd.map))
      (field $hd.iterator-index (mut i32))
      (field $hd.iterator-version i32)))
    (type $hd.map (struct
      (field $hd.map-key-kind i32)
      (field $hd.map-size (mut i32))
      (field $hd.map-keys (mut (ref $hd.list)))
      (field $hd.map-values (mut (ref $hd.list)))
      (field $hd.map-version (mut i32))))
    (type $hd.providers (struct
      (field $hd.provider-key i32)
      (field $hd.provider-value anyref)
      (field $hd.provider-parent (ref null $hd.providers))))
    (type $hd.box-i32 (struct
      (field $hd.box-i32-value i32)))
    (type $hd.box-f64 (struct
      (field $hd.box-f64-value f64)))
    (type $hd.box-extern (struct
      (field $hd.box-extern-value externref)))
    (type $hd.variant (struct
      (field $hd.variant-tag i32)
      (field $hd.variant-payload (mut anyref))))
    (type $closure0 (struct
      (field $closure0fn (ref $sig0))
      (field $closure0env anyref)))
    (type $closure1 (struct
      (field $closure1fn (ref $sig1))
      (field $closure1env anyref)))
    (type $closure2 (struct
      (field $closure2fn (ref $sig2))
      (field $closure2env anyref)))
    (type $closure3 (struct
      (field $closure3fn (ref $sig3))
      (field $closure3env anyref)))
    (type $closure4 (struct
      (field $closure4fn (ref $sig4))
      (field $closure4env anyref)))
    (type $closure5 (struct
      (field $closure5fn (ref $sig5))
      (field $closure5env anyref)))
    (type $closure6 (struct
      (field $closure6fn (ref $sig6))
      (field $closure6env anyref)))
    (type $trait0 (struct
      (field $trait0value anyref)
      (field $trait0bounds (ref null $hd.list))
      (field $trait0m0 (ref $tsig0_0))))
    (type $trait1 (struct
      (field $trait1value anyref)
      (field $trait1bounds (ref null $hd.list))
      (field $trait1m0 (ref $tsig1_0))))
    (type $trait2 (struct
      (field $trait2value anyref)
      (field $trait2bounds (ref null $hd.list))
      (field $trait2m0 (ref $tsig2_0))
      (field $trait2s0 (ref null $trait1))))
    (type $trait3 (struct
      (field $trait3value anyref)
      (field $trait3bounds (ref null $hd.list))
      (field $trait3m0 (ref $tsig3_0))))
    (type $trait4 (struct
      (field $trait4value anyref)
      (field $trait4bounds (ref null $hd.list))
      (field $trait4m0 (ref $tsig4_0))))
    (type $trait5 (struct
      (field $trait5value anyref)
      (field $trait5bounds (ref null $hd.list))
      (field $trait5m0 (ref $tsig5_0))))
    (type $trait6 (struct
      (field $trait6value anyref)
      (field $trait6bounds (ref null $hd.list))
      (field $trait6m0 (ref $tsig6_0))))
    (type $trait7 (struct
      (field $trait7value anyref)
      (field $trait7bounds (ref null $hd.list))
      (field $trait7m0 (ref $tsig7_0))))
    (type $s15 (struct
      (field $s15state (mut i32))
      (field $s15polls (mut i32))
      (field $s15a0 i32)
      (field $s15result (mut i32))))
    (type $s16 (struct
      (field $s16state (mut i32))
      (field $s16polls (mut i32))
      (field $s16a0 i32)
      (field $s16l1 (mut i32))
      (field $s16l2 (mut i32))
      (field $s16l3 (mut i32))
      (field $s16l4 (mut i32))
      (field $s16l5 (mut i32))
      (field $s16l6 (mut i32))
      (field $s16l7 (mut i32))
      (field $s16l8 (mut i32))
      (field $s16l9 (mut i32))
      (field $s16l10 (mut i32))
      (field $s16l11 (mut i32))
      (field $s16l12 (mut i32))
      (field $s16l13 (mut i32))
      (field $s16child0 (mut (ref null $s15)))
      (field $s16result (mut i32))))
    (type $env0 (struct
      (field $env0f0 i32)))
    (type $env1 (struct
      (field $env1f0 i32)))
    (type $d0 (struct
      (field $d0f0 (mut i32))))
    (type $e0 (struct
      (field $e0tag i32)))
    (type $hd.runtime (struct
      (field $status (mut i32))
      (field $scratch (mut (ref null $hd.bytes)))))
  )

(global $e0v0 (ref $e0)
    (struct.new $e0 (i32.const 0)))

(global $e0v1 (ref $e0)
    (struct.new $e0 (i32.const 1)))

(global $e0v2 (ref $e0)
    (struct.new $e0 (i32.const 2)))

(func $f0 (param $l0 (ref null $hd.vector)) (result i32)
    (local $l1 i32)
    (local $l2 anyref)
    (local $tmp0 (ref null $hd.iterator))
    (local $tmp1 (ref null $hd.variant))
    (local $tmp2 anyref)
    (local $tmp3 (ref null $hd.vector))
    (local $tmp4 (ref null $hd.iterator))
    (local $tmp5 (ref null $hd.variant))
    (local.set $l1 (i32.const 0))
    (block $break0
      (local.set $tmp0 (block (result (ref null $hd.iterator))
      (local.set $tmp3 (local.get $l0))
      (struct.new $hd.iterator
        (ref.as_non_null (local.get $tmp3))
        (ref.null $hd.map)
        (i32.const 0)
        (struct.get $hd.vector $hd.vector-version (ref.as_non_null (local.get $tmp3))))
    ))
      (loop $loop0
        (local.set $tmp1 (block (result (ref null $hd.variant))
          (local.set $tmp4 (local.get $tmp0))
          (if (result (ref null $hd.variant))
            (ref.is_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))
            (then (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.map $hd.map-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp4))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (struct.get $hd.map $hd.map-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp5
                (struct.new $hd.variant (i32.const 1) (array.new_fixed $hd.list 2 (array.get $hd.list (struct.get $hd.map $hd.map-keys (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4)))) (array.get $hd.list (struct.get $hd.map $hd.map-values (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4)))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (i32.const 1)))
              (local.get $tmp5)))
        ))
            (else (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.vector $hd.vector-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp4))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp5
                (struct.new $hd.variant (i32.const 1) (call $hd.vector_get (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4)))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (i32.const 1)))
              (local.get $tmp5)))
        )))
        ))
        (br_if $break0 (i32.eqz (struct.get $hd.variant $hd.variant-tag (ref.as_non_null (local.get $tmp1)))))
        (local.set $tmp2 (struct.get $hd.variant $hd.variant-payload (ref.as_non_null (local.get $tmp1))))
        (local.set $l2 (local.get $tmp2))
        (block $continue0
          (local.set $l1 (call $hd.add_i32 (local.get $l1) (i32.const 1)))
        )
        (br $loop0)
      )
    )
    (local.get $l1)
  )

(func $f1 (param $l0 (ref null $hd.vector)) (result anyref)
    (call $hd.vector_get (ref.as_non_null (local.get $l0)) (i32.const 0))
  )

(func $f2 (param $l0 anyref) (param $bound0 (ref null $trait0)) (result i32)
    (local $tmp0 (ref null $trait0))
    (block (result i32)
      (local.set $tmp0 (struct.new $trait0 (local.get $l0) (struct.get $trait0 $trait0bounds (local.get $bound0)) (struct.get $trait0 $trait0m0 (local.get $bound0))))
      (call_ref $tsig0_0
      (struct.get $trait0 $trait0value (local.get $tmp0))
      (local.get $tmp0)
      (struct.get $trait0 $trait0m0 (local.get $tmp0)))
    )
  )

(func $f3 (param $l0 anyref) (param $bound0 (ref null $trait2)) (result i32)
    (local $tmp0 (ref null $trait2))
    (block (result i32)
      (local.set $tmp0 (struct.new $trait2 (local.get $l0) (struct.get $trait2 $trait2bounds (local.get $bound0)) (struct.get $trait2 $trait2m0 (local.get $bound0)) (struct.get $trait2 $trait2s0 (local.get $bound0))))
      (call_ref $tsig1_0
      (struct.get $trait2 $trait2value (local.get $tmp0))
      (struct.get $trait2 $trait2s0 (local.get $tmp0))
      (struct.get $trait1 $trait1m0 (struct.get $trait2 $trait2s0 (local.get $tmp0))))
    )
  )

(func $f4 (param $l0 i32) (result (ref null $hd.vector))
    (local $l1 (ref null $hd.vector))
    (local $l2 i32)
    (local $tmp0 i32)
    (local.set $l1 (struct.new $hd.vector (i32.const 0) (array.new_default $hd.list (i32.const 0)) (i32.const 0)))
    (local.set $l2 (i32.const 0))
    (block $break1
      (loop $loop1
        (br_if $break1 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l2) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (call $hd.vector_append (ref.as_non_null (local.get $l1)) (struct.new $hd.box-i32 (local.get $l2)))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (i32.const 1)))
        (br $loop1)
      )
    )
    (local.get $l1)
  )

(func $fv4 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.vector))
    (call $f4 (local.get $l0))
  )

(func $f5 (export "loop_empty") (param $l0 i32) (result i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $tmp0 i32)
    (local.set $l1 (i32.const 0))
    (local.set $l2 (i32.const 0))
    (block $break2
      (loop $loop2
        (br_if $break2 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l2) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l1 (call $hd.add_i32 (local.get $l1) (local.get $l2)))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (i32.const 1)))
        (br $loop2)
      )
    )
    (local.get $l1)
  )

(func $fv5 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f5 (local.get $l0))
  )

(func $f6 (export "loop_for_concrete") (param $l0 i32) (result i32)
    (local $l1 (ref null $hd.vector))
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 (ref null $hd.iterator))
    (local $tmp1 (ref null $hd.variant))
    (local $tmp2 i32)
    (local $tmp3 (ref null $hd.vector))
    (local $tmp4 (ref null $hd.iterator))
    (local $tmp5 (ref null $hd.variant))
    (local.set $l1 (call $f4 (local.get $l0)))
    (local.set $l2 (i32.const 0))
    (block $break3
      (local.set $tmp0 (block (result (ref null $hd.iterator))
      (local.set $tmp3 (local.get $l1))
      (struct.new $hd.iterator
        (ref.as_non_null (local.get $tmp3))
        (ref.null $hd.map)
        (i32.const 0)
        (struct.get $hd.vector $hd.vector-version (ref.as_non_null (local.get $tmp3))))
    ))
      (loop $loop3
        (local.set $tmp1 (block (result (ref null $hd.variant))
          (local.set $tmp4 (local.get $tmp0))
          (if (result (ref null $hd.variant))
            (ref.is_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))
            (then (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.map $hd.map-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp4))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (struct.get $hd.map $hd.map-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp5
                (struct.new $hd.variant (i32.const 1) (array.new_fixed $hd.list 2 (array.get $hd.list (struct.get $hd.map $hd.map-keys (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4)))) (array.get $hd.list (struct.get $hd.map $hd.map-values (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4)))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (i32.const 1)))
              (local.get $tmp5)))
        ))
            (else (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.vector $hd.vector-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp4))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp5
                (struct.new $hd.variant (i32.const 1) (call $hd.vector_get (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4)))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (i32.const 1)))
              (local.get $tmp5)))
        )))
        ))
        (br_if $break3 (i32.eqz (struct.get $hd.variant $hd.variant-tag (ref.as_non_null (local.get $tmp1)))))
        (local.set $tmp2 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (struct.get $hd.variant $hd.variant-payload (ref.as_non_null (local.get $tmp1))))))
        (local.set $l3 (local.get $tmp2))
        (block $continue3
          (local.set $l2 (call $hd.add_i32 (local.get $l2) (local.get $l3)))
        )
        (br $loop3)
      )
    )
    (local.get $l2)
  )

(func $fv6 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f6 (local.get $l0))
  )

(func $f7 (export "loop_for_generic") (param $l0 i32) (result i32)
    (local $l1 (ref null $hd.vector))
    (local.set $l1 (call $f4 (local.get $l0)))
    (call $f0 (local.get $l1))
  )

(func $fv7 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f7 (local.get $l0))
  )

(func $f8 (export "loop_generic_call") (param $l0 i32) (result i32)
    (local $l1 (ref null $hd.vector))
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 i32)
    (local.set $l1 (call $f4 (i32.const 1)))
    (local.set $l2 (i32.const 0))
    (local.set $l3 (i32.const 0))
    (block $break4
      (loop $loop4
        (br_if $break4 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l3) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l3) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $f1 (local.get $l1))))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (i32.const 1)))
        (br $loop4)
      )
    )
    (local.get $l2)
  )

(func $fv8 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f8 (local.get $l0))
  )

(func $f9 (export "loop_closure_call") (param $l0 i32) (result i32)
    (local $l1 i32)
    (local $l2 (ref null $closure1))
    (local $l3 i32)
    (local $l4 i32)
    (local $tmp0 (ref null $closure1))
    (local $tmp1 i32)
    (local.set $l1 (i32.const 1))
    (local.set $l2 (struct.new $closure1 (ref.func $c0) (struct.new $env0 (local.get $l1))))
    (local.set $l3 (i32.const 0))
    (local.set $l4 (i32.const 0))
    (block $break5
      (loop $loop5
        (br_if $break5 (i32.eqz (block (result i32) (local.set $tmp1 (if (result i32) (i32.lt_s (local.get $l4) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l4) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp1) (i32.const -1)))))
        (local.set $l3 (block (result i32)
          (local.set $tmp0 (local.get $l2))
          (call_ref $sig1
            (struct.get $closure1 $closure1env (local.get $tmp0))
            (local.get $l3)
            (struct.get $closure1 $closure1fn (local.get $tmp0)))
        ))
        (local.set $l4 (call $hd.add_i32 (local.get $l4) (i32.const 1)))
        (br $loop5)
      )
    )
    (local.get $l3)
  )

(func $fv9 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f9 (local.get $l0))
  )

(func $f10 (export "loop_closure_create") (param $l0 i32) (result i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 (ref null $closure1))
    (local $tmp0 (ref null $closure1))
    (local $tmp1 i32)
    (local.set $l1 (i32.const 1))
    (local.set $l2 (i32.const 0))
    (local.set $l3 (i32.const 0))
    (block $break6
      (loop $loop6
        (br_if $break6 (i32.eqz (block (result i32) (local.set $tmp1 (if (result i32) (i32.lt_s (local.get $l3) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l3) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp1) (i32.const -1)))))
        (local.set $l4 (struct.new $closure1 (ref.func $c1) (struct.new $env1 (local.get $l1))))
        (local.set $l2 (block (result i32)
          (local.set $tmp0 (local.get $l4))
          (call_ref $sig1
            (struct.get $closure1 $closure1env (local.get $tmp0))
            (local.get $l2)
            (struct.get $closure1 $closure1fn (local.get $tmp0)))
        ))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (i32.const 1)))
        (br $loop6)
      )
    )
    (local.get $l2)
  )

(func $fv10 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f10 (local.get $l0))
  )

(func $f11 (export "loop_interpolation") (param $l0 i32) (result i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 (ref null $hd.bytes))
    (local $tmp0 i32)
    (local.set $l1 (i32.const 0))
    (local.set $l2 (i32.const 0))
    (block $break7
      (loop $loop7
        (br_if $break7 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l2) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l3 (call $hd.string_concat (call $hd.string_concat (call $hd.string_concat (array.new_fixed $hd.bytes 5 (i32.const 105) (i32.const 116) (i32.const 101) (i32.const 109) (i32.const 32)) (call $hd.i32_to_string (local.get $l2))) (array.new_fixed $hd.bytes 4 (i32.const 32) (i32.const 111) (i32.const 102) (i32.const 32))) (call $hd.i32_to_string (local.get $l0))))
        (local.set $l1 (call $hd.add_i32 (local.get $l1) (call $hd.string_len (local.get $l3))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (i32.const 1)))
        (br $loop7)
      )
    )
    (local.get $l1)
  )

(func $fv11 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f11 (local.get $l0))
  )

(func $f12 (export "loop_bounded") (param $l0 i32) (result i32)
    (local $l1 (ref null $d0))
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 i32)
    (local $tmp1 i32)
    (local.set $l1 (block (result (ref null $d0))
      (local.set $tmp0 (i32.const 1))
      (struct.new $d0 (local.get $tmp0))
    ))
    (local.set $l2 (i32.const 0))
    (local.set $l3 (i32.const 0))
    (block $break8
      (loop $loop8
        (br_if $break8 (i32.eqz (block (result i32) (local.set $tmp1 (if (result i32) (i32.lt_s (local.get $l3) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l3) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp1) (i32.const -1)))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (call $f2 (local.get $l1) (struct.new $trait0 (ref.null any) (ref.null $hd.list) (ref.func $tadapt0_0)))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (i32.const 1)))
        (br $loop8)
      )
    )
    (local.get $l2)
  )

(func $fv12 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f12 (local.get $l0))
  )

(func $f13 (export "loop_supertrait") (param $l0 i32) (result i32)
    (local $l1 (ref null $d0))
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 i32)
    (local $tmp1 i32)
    (local.set $l1 (block (result (ref null $d0))
      (local.set $tmp0 (i32.const 1))
      (struct.new $d0 (local.get $tmp0))
    ))
    (local.set $l2 (i32.const 0))
    (local.set $l3 (i32.const 0))
    (block $break9
      (loop $loop9
        (br_if $break9 (i32.eqz (block (result i32) (local.set $tmp1 (if (result i32) (i32.lt_s (local.get $l3) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l3) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp1) (i32.const -1)))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (call $f3 (local.get $l1) (struct.new $trait2 (ref.null any) (ref.null $hd.list) (ref.func $tadapt2_0) (struct.new $trait1 (ref.null any) (ref.null $hd.list) (ref.func $tadapt1_0))))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (i32.const 1)))
        (br $loop9)
      )
    )
    (local.get $l2)
  )

(func $fv13 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f13 (local.get $l0))
  )

(func $f14 (export "loop_blanket") (param $l0 i32) (result i32)
    (local $l1 (ref null $hd.vector))
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 i32)
    (local $tmp1 i32)
    (local.set $l1 (struct.new $hd.vector (i32.const 1) (array.new_fixed $hd.list 1 (block (result (ref null $d0))
      (local.set $tmp0 (i32.const 1))
      (struct.new $d0 (local.get $tmp0))
    )) (i32.const 0)))
    (local.set $l2 (i32.const 0))
    (local.set $l3 (i32.const 0))
    (block $break10
      (loop $loop10
        (br_if $break10 (i32.eqz (block (result i32) (local.set $tmp1 (if (result i32) (i32.lt_s (local.get $l3) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l3) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp1) (i32.const -1)))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (call $f3 (local.get $l1) (struct.new $trait2 (ref.null any) (array.new_fixed $hd.list 1 (struct.new $trait0 (ref.null any) (ref.null $hd.list) (ref.func $tadapt0_0))) (ref.func $tadapt4_0) (struct.new $trait1 (ref.null any) (array.new_fixed $hd.list 1 (struct.new $trait0 (ref.null any) (ref.null $hd.list) (ref.func $tadapt0_0))) (ref.func $tadapt3_0))))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (i32.const 1)))
        (br $loop10)
      )
    )
    (local.get $l2)
  )

(func $fv14 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f14 (local.get $l0))
  )

(func $body15 (param $l0 i32) (result i32)
    (call $hd.add_i32 (local.get $l0) (i32.const 1))
  )

(func $f15 (param $l0 i32) (result (ref null $s15))
    (call $hd.trace (i32.const 15) (i32.const 0))
    (struct.new $s15 (i32.const 0) (i32.const 0) (local.get $l0) (i32.const 0))
  )

(func $poll15 (param $frame (ref null $s15)) (result i32)
    (call $hd.trace (i32.const 15) (i32.const 1))
    (if (i32.eq (struct.get $s15 $s15state (local.get $frame)) (i32.const 1))
      (then (call $hd.trace (i32.const 15) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or
          (i32.eq (struct.get $s15 $s15state (local.get $frame)) (i32.const 2))
          (i32.eq (struct.get $s15 $s15state (local.get $frame)) (i32.const 3)))
      (then (call $hd.trace (i32.const 15) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s15 $s15polls (local.get $frame)
      (i32.add (struct.get $s15 $s15polls (local.get $frame)) (i32.const 1)))
    (struct.set $s15 $s15state (local.get $frame) (i32.const 1))
    (if (call $hd.pending
          (i32.const 15)
          (struct.get $s15 $s15polls (local.get $frame)))
      (then
        (struct.set $s15 $s15state (local.get $frame) (i32.const 4))
        (call $hd.trace (i32.const 15) (i32.const 6))
        (return (i32.const 0))))
    (struct.set $s15 $s15state (local.get $frame) (i32.const 1))
    (struct.set $s15 $s15result (local.get $frame) (call $body15 (struct.get $s15 $s15a0 (local.get $frame))))
    (struct.set $s15 $s15state (local.get $frame) (i32.const 2))
    (call $hd.trace (i32.const 15) (i32.const 2))
    (i32.const 1)
  )

(func $drive15 (param $frame (ref null $s15)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll15 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s15 $s15result (local.get $frame))
  )

(func $cancel15 (param $frame (ref null $s15))
    (call $hd.trace (i32.const 15) (i32.const 3))
    (if (i32.eq (struct.get $s15 $s15state (local.get $frame)) (i32.const 1))
      (then (call $hd.trace (i32.const 15) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or
          (i32.eq (struct.get $s15 $s15state (local.get $frame)) (i32.const 0))
          (i32.eq (struct.get $s15 $s15state (local.get $frame)) (i32.const 4)))
      (then (struct.set $s15 $s15state (local.get $frame) (i32.const 3))))
  )

(func $fv15 (type $sig2) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f15 (local.get $l0)) (ref.func $swpoll15) (ref.func $swcancel15) (ref.func $swresult15))
  )

(func $f16 (param $l0 i32) (result (ref null $s16))
    (call $hd.trace (i32.const 16) (i32.const 0))
    (struct.new $s16 (i32.const 0) (i32.const 0) (local.get $l0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (ref.null $s15) (i32.const 0))
  )

(func $poll16 (param $frame (ref null $s16)) (result i32)
    (local $resume-state i32)
    (local $pc i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (local $l5 i32)
    (local $l6 i32)
    (local $l7 i32)
    (local $l8 i32)
    (local $l9 i32)
    (local $l10 i32)
    (local $l11 i32)
    (local $l12 i32)
    (local $l13 i32)
    (local $tmp0 i32)
    (call $hd.trace (i32.const 16) (i32.const 1))
    (local.set $resume-state (struct.get $s16 $s16state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 16) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 2)) (i32.eq (local.get $resume-state) (i32.const 3)))
      (then (call $hd.trace (i32.const 16) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s16 $s16polls (local.get $frame)
      (i32.add (struct.get $s16 $s16polls (local.get $frame)) (i32.const 1)))
    (struct.set $s16 $s16state (local.get $frame) (i32.const 1))
    (if (call $hd.pending (i32.const 16) (struct.get $s16 $s16polls (local.get $frame)))
      (then
        (struct.set $s16 $s16state (local.get $frame)
          (if (result i32) (i32.eq (local.get $resume-state) (i32.const 0))
            (then (i32.const 4))
            (else (local.get $resume-state))))
        (call $hd.trace (i32.const 16) (i32.const 6))
        (return (i32.const 0))))
    (local.set $l0 (struct.get $s16 $s16a0 (local.get $frame)))
    (local.set $l1 (struct.get $s16 $s16l1 (local.get $frame)))
    (local.set $l2 (struct.get $s16 $s16l2 (local.get $frame)))
    (local.set $l3 (struct.get $s16 $s16l3 (local.get $frame)))
    (local.set $l4 (struct.get $s16 $s16l4 (local.get $frame)))
    (local.set $l5 (struct.get $s16 $s16l5 (local.get $frame)))
    (local.set $l6 (struct.get $s16 $s16l6 (local.get $frame)))
    (local.set $l7 (struct.get $s16 $s16l7 (local.get $frame)))
    (local.set $l8 (struct.get $s16 $s16l8 (local.get $frame)))
    (local.set $l9 (struct.get $s16 $s16l9 (local.get $frame)))
    (local.set $l10 (struct.get $s16 $s16l10 (local.get $frame)))
    (local.set $l11 (struct.get $s16 $s16l11 (local.get $frame)))
    (local.set $l12 (struct.get $s16 $s16l12 (local.get $frame)))
    (local.set $l13 (struct.get $s16 $s16l13 (local.get $frame)))
    (struct.set $s16 $s16state (local.get $frame) (i32.const 1))
    (if (i32.le_u (local.get $resume-state) (i32.const 4))
      (then (local.set $pc (i32.const 18)))
      (else
        (if (i32.eq (local.get $resume-state) (i32.const 5))
          (then
            (if (i32.eqz (call $poll15 (struct.get $s16 $s16child0 (local.get $frame))))
              (then
                (struct.set $s16 $s16l1 (local.get $frame) (local.get $l1))
                (struct.set $s16 $s16l2 (local.get $frame) (local.get $l2))
                (struct.set $s16 $s16l3 (local.get $frame) (local.get $l3))
                (struct.set $s16 $s16l4 (local.get $frame) (local.get $l4))
                (struct.set $s16 $s16l5 (local.get $frame) (local.get $l5))
                (struct.set $s16 $s16l6 (local.get $frame) (local.get $l6))
                (struct.set $s16 $s16l7 (local.get $frame) (local.get $l7))
                (struct.set $s16 $s16l8 (local.get $frame) (local.get $l8))
                (struct.set $s16 $s16l9 (local.get $frame) (local.get $l9))
                (struct.set $s16 $s16l10 (local.get $frame) (local.get $l10))
                (struct.set $s16 $s16l11 (local.get $frame) (local.get $l11))
                (struct.set $s16 $s16l12 (local.get $frame) (local.get $l12))
                (struct.set $s16 $s16l13 (local.get $frame) (local.get $l13))
                (struct.set $s16 $s16state (local.get $frame) (local.get $resume-state))
                (call $hd.trace (i32.const 16) (i32.const 6))
                (return (i32.const 0))))
            (local.set $l6 (struct.get $s15 $s15result (struct.get $s16 $s16child0 (local.get $frame))))
            (local.set $pc (i32.const 10))
          )
          (else
            (local.set $pc (i32.const 18))
          ))
      ))
    (loop $cfg
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (local.set $l3 (local.get $l1))
          (struct.set $s16 $s16result (local.get $frame) (local.get $l3))
          (struct.set $s16 $s16state (local.get $frame) (i32.const 2))
          (call $hd.trace (i32.const 16) (i32.const 2))
          (return (i32.const 1))
        ))
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $pc (i32.const 0))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $pc (i32.const 16))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $pc (i32.const 2))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $l2 (call $hd.add_i32 (local.get $l10) (local.get $l11)))
          (local.set $pc (i32.const 3))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $l11 (i32.const 1))
          (local.set $pc (i32.const 4))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $l10 (local.get $l2))
          (local.set $pc (i32.const 5))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $l1 (call $hd.sub_i32 (local.get $l8) (local.get $l9)))
          (local.set $pc (i32.const 6))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (local.set $l9 (local.get $l2))
          (local.set $pc (i32.const 7))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (local.set $l8 (call $hd.add_i32 (local.get $l4) (local.get $l7)))
          (local.set $pc (i32.const 8))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (local.set $l7 (local.get $l6))
          (local.set $pc (i32.const 9))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 11))
        (then
          (struct.set $s16 $s16child0 (local.get $frame) (call $f15 (local.get $l5)))
          (if (i32.eqz (call $poll15 (struct.get $s16 $s16child0 (local.get $frame))))
            (then
              (struct.set $s16 $s16l1 (local.get $frame) (local.get $l1))
              (struct.set $s16 $s16l2 (local.get $frame) (local.get $l2))
              (struct.set $s16 $s16l3 (local.get $frame) (local.get $l3))
              (struct.set $s16 $s16l4 (local.get $frame) (local.get $l4))
              (struct.set $s16 $s16l5 (local.get $frame) (local.get $l5))
              (struct.set $s16 $s16l6 (local.get $frame) (local.get $l6))
              (struct.set $s16 $s16l7 (local.get $frame) (local.get $l7))
              (struct.set $s16 $s16l8 (local.get $frame) (local.get $l8))
              (struct.set $s16 $s16l9 (local.get $frame) (local.get $l9))
              (struct.set $s16 $s16l10 (local.get $frame) (local.get $l10))
              (struct.set $s16 $s16l11 (local.get $frame) (local.get $l11))
              (struct.set $s16 $s16l12 (local.get $frame) (local.get $l12))
              (struct.set $s16 $s16l13 (local.get $frame) (local.get $l13))
              (struct.set $s16 $s16state (local.get $frame) (i32.const 5))
              (call $hd.trace (i32.const 16) (i32.const 6))
              (return (i32.const 0))))
          (local.set $l6 (struct.get $s15 $s15result (struct.get $s16 $s16child0 (local.get $frame))))
          (local.set $pc (i32.const 10))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 12))
        (then
          (local.set $l5 (local.get $l2))
          (local.set $pc (i32.const 11))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 13))
        (then
          (local.set $l4 (local.get $l1))
          (local.set $pc (i32.const 12))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 14))
        (then
          (if (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l12) (local.get $l13)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l12) (local.get $l13)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))
            (then (local.set $pc (i32.const 13)))
            (else (local.set $pc (i32.const 1))))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 15))
        (then
          (local.set $l13 (local.get $l0))
          (local.set $pc (i32.const 14))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 16))
        (then
          (local.set $l12 (local.get $l2))
          (local.set $pc (i32.const 15))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 17))
        (then
          (local.set $l2 (i32.const 0))
          (local.set $pc (i32.const 2))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 18))
        (then
          (local.set $l1 (i32.const 0))
          (local.set $pc (i32.const 17))
          (br $cfg)
        ))
      unreachable
    )
  )

(func $drive16 (param $frame (ref null $s16)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll16 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s16 $s16result (local.get $frame))
  )

(func $cancel16 (param $frame (ref null $s16))
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (local $l5 i32)
    (local $l6 i32)
    (local $l7 i32)
    (local $l8 i32)
    (local $l9 i32)
    (local $l10 i32)
    (local $l11 i32)
    (local $l12 i32)
    (local $l13 i32)
    (local $tmp0 i32)
    (call $hd.trace (i32.const 16) (i32.const 3))
    (local.set $resume-state (struct.get $s16 $s16state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 16) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (local.set $l0 (struct.get $s16 $s16a0 (local.get $frame)))
    (local.set $l1 (struct.get $s16 $s16l1 (local.get $frame)))
    (local.set $l2 (struct.get $s16 $s16l2 (local.get $frame)))
    (local.set $l3 (struct.get $s16 $s16l3 (local.get $frame)))
    (local.set $l4 (struct.get $s16 $s16l4 (local.get $frame)))
    (local.set $l5 (struct.get $s16 $s16l5 (local.get $frame)))
    (local.set $l6 (struct.get $s16 $s16l6 (local.get $frame)))
    (local.set $l7 (struct.get $s16 $s16l7 (local.get $frame)))
    (local.set $l8 (struct.get $s16 $s16l8 (local.get $frame)))
    (local.set $l9 (struct.get $s16 $s16l9 (local.get $frame)))
    (local.set $l10 (struct.get $s16 $s16l10 (local.get $frame)))
    (local.set $l11 (struct.get $s16 $s16l11 (local.get $frame)))
    (local.set $l12 (struct.get $s16 $s16l12 (local.get $frame)))
    (local.set $l13 (struct.get $s16 $s16l13 (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 5))
      (then
        (call $cancel15 (struct.get $s16 $s16child0 (local.get $frame)))
        (struct.set $s16 $s16state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 0)) (i32.eq (local.get $resume-state) (i32.const 4)))
      (then (struct.set $s16 $s16state (local.get $frame) (i32.const 3))))
  )

(func $fv16 (type $sig2) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f16 (local.get $l0)) (ref.func $swpoll16) (ref.func $swcancel16) (ref.func $swresult16))
  )

(func $f17 (export "loop_suspend_ready") (param $l0 i32) (result i32)
    (local $l1 (ref null $hd.suspension))
    (local.set $l1 (struct.new $hd.suspension (call $f16 (local.get $l0)) (ref.func $swpoll16) (ref.func $swcancel16) (ref.func $swresult16)))
    (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (block (result anyref) (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 3)) unreachable)) (call $hd.suspension_drive (local.get $l1)))))
  )

(func $fv17 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $f17 (local.get $l0))
  )

(func $f18 (export "tick") (param $provider0 externref) (result i32)
    (drop (local.get $provider0))
    (i32.const 1)
  )

(func $fv18 (type $sig3) (param $env anyref) (param $provider0 externref) (result i32)
    (call $f18 (local.get $provider0))
  )

(func $f19 (export "loop_requirement") (param $l0 i32) (param $provider0 externref) (result i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $tmp0 i32)
    (local.set $l1 (i32.const 0))
    (local.set $l2 (i32.const 0))
    (block $break11
      (loop $loop11
        (br_if $break11 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l2) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l1 (call $hd.add_i32 (local.get $l1) (call $f18 (local.get $provider0))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (i32.const 1)))
        (br $loop11)
      )
    )
    (local.get $l1)
  )

(func $fv19 (type $sig4) (param $env anyref) (param $l0 i32) (param $provider0 externref) (result i32)
    (call $f19 (local.get $l0) (local.get $provider0))
  )

(func $f20 (export "loop_with") (param $l0 i32) (param $provider0 externref) (result i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 externref)
    (local $tmp0 i32)
    (local.set $l1 (i32.const 0))
    (local.set $l2 (i32.const 0))
    (block $break12
      (loop $loop12
        (br_if $break12 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l2) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (block
          (local.set $l3 (local.get $provider0))
          (local.set $l1 (call $hd.add_i32 (local.get $l1) (call $f18 (local.get $l3))))
        )
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (i32.const 1)))
        (br $loop12)
      )
    )
    (local.get $l1)
  )

(func $fv20 (type $sig4) (param $env anyref) (param $l0 i32) (param $provider0 externref) (result i32)
    (call $f20 (local.get $l0) (local.get $provider0))
  )

(func $f21 (export "main") (result i32)
    (i32.const 0)
  )

(func $fv21 (type $sig5) (param $env anyref)  (result i32)
    (call $f21)
  )

(func $f22 (param $l0 (ref null $d0)) (result i32)
    (struct.get $d0 $d0f0 (local.get $l0))
  )

(func $fv22 (type $sig6) (param $env anyref) (param $l0 (ref null $d0)) (result i32)
    (call $f22 (local.get $l0))
  )

(func $f23 (param $l0 (ref null $d0)) (result i32)
    (struct.get $d0 $d0f0 (local.get $l0))
  )

(func $fv23 (type $sig6) (param $env anyref) (param $l0 (ref null $d0)) (result i32)
    (call $f23 (local.get $l0))
  )

(func $f24 (param $l0 (ref null $d0)) (result i32)
    (i32.const 0)
  )

(func $fv24 (type $sig6) (param $env anyref) (param $l0 (ref null $d0)) (result i32)
    (call $f24 (local.get $l0))
  )

(func $f25 (param $l0 (ref null $hd.vector)) (param $bound0 (ref null $trait0)) (result i32)
    (local $tmp0 (ref null $trait0))
    (block (result i32)
      (local.set $tmp0 (struct.new $trait0 (call $hd.vector_get (ref.as_non_null (local.get $l0)) (i32.const 0)) (struct.get $trait0 $trait0bounds (local.get $bound0)) (struct.get $trait0 $trait0m0 (local.get $bound0))))
      (call_ref $tsig0_0
      (struct.get $trait0 $trait0value (local.get $tmp0))
      (local.get $tmp0)
      (struct.get $trait0 $trait0m0 (local.get $tmp0)))
    )
  )

(func $f26 (param $l0 (ref null $hd.vector)) (param $bound0 (ref null $trait0)) (result i32)
    (i32.const 0)
  )

(func $c0 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $hd.add_i32 (local.get $l0) (struct.get $env0 $env0f0 (ref.cast (ref $env0) (local.get $env))))
  )

(func $c1 (type $sig1) (param $env anyref) (param $l0 i32) (result i32)
    (call $hd.add_i32 (local.get $l0) (struct.get $env1 $env1f0 (ref.cast (ref $env1) (local.get $env))))
  )

(func $swpoll15 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll15 (ref.cast (ref $s15) (local.get $inner))))

(func $swcancel15 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel15 (ref.cast (ref $s15) (local.get $inner))))

(func $swresult15 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s15 $s15result (ref.cast (ref $s15) (local.get $inner)))))

(func $swpoll16 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll16 (ref.cast (ref $s16) (local.get $inner))))

(func $swcancel16 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel16 (ref.cast (ref $s16) (local.get $inner))))

(func $swresult16 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s16 $s16result (ref.cast (ref $s16) (local.get $inner)))))

(func $tadapt0_0 (type $tsig0_0) (param $self anyref) (param $dictionary anyref)  (result i32)
    (call $f22 (ref.cast (ref null $d0) (local.get $self)))
  )

(func $tadapt1_0 (type $tsig1_0) (param $self anyref) (param $dictionary anyref)  (result i32)
    (call $f23 (ref.cast (ref null $d0) (local.get $self)))
  )

(func $tadapt2_0 (type $tsig2_0) (param $self anyref) (param $dictionary anyref)  (result i32)
    (call $f24 (ref.cast (ref null $d0) (local.get $self)))
  )

(func $tadapt3_0 (type $tsig1_0) (param $self anyref) (param $dictionary anyref)  (result i32)
    (call $f25 (ref.cast (ref null $hd.vector) (local.get $self)) (ref.cast (ref null $trait0) (array.get $hd.list (ref.as_non_null (struct.get $trait1 $trait1bounds (ref.cast (ref $trait1) (local.get $dictionary)))) (i32.const 0))))
  )

(func $tadapt4_0 (type $tsig2_0) (param $self anyref) (param $dictionary anyref)  (result i32)
    (call $f26 (ref.cast (ref null $hd.vector) (local.get $self)) (ref.cast (ref null $trait0) (array.get $hd.list (ref.as_non_null (struct.get $trait2 $trait2bounds (ref.cast (ref $trait2) (local.get $dictionary)))) (i32.const 0))))
  )
