;; commit bd985d7; command: erasure-excerpts.ts (emitWat of audit/probes/arch/alloc/alloc-frames.hd); date: 2026-09-25T20:54:17.628Z
(rec
    (type $sig0 (func (param anyref) (param i32) (result (ref null $hd.suspension))))
    (type $tsig0_0 (func (param anyref) (param anyref) (result (ref null $hd.bytes))))
    (type $tsig1_0 (func (param anyref) (param anyref) (param anyref) (result i32)))
    (type $tsig2_0 (func (param anyref) (param anyref) (param anyref) (result (ref null $hd.variant))))
    (type $tsig3_0 (func (param anyref) (param anyref)))
    (type $tsig4_0 (func (param anyref) (param anyref) (result (ref null $hd.variant))))
    (type $hd.suspension-poll-sig (func (param anyref) (result i32)))
    (type $hd.suspension-cancel-sig (func (param anyref)))
    (type $hd.suspension-result-sig (func (param anyref) (result anyref)))
    (type $hd.suspension (struct
      (field $hd.suspension-inner anyref)
      (field $hd.suspension-poll (ref $hd.suspension-poll-sig))
      (field $hd.suspension-cancel (ref $hd.suspension-cancel-sig))
      (field $hd.suspension-result (ref $hd.suspension-result-sig))))
    (type $hd.bytes (array (mut i8)))
    (type $hd.list (array (mut anyref)))
    (type $hd.vector (struct
      (field $hd.vector-size (mut i32))
      (field $hd.vector-values (mut (ref $hd.list)))
      (field $hd.vector-version (mut i32))))
    (type $hd.iterator (struct
      (field $hd.iterator-list (ref null $hd.vector))
      (field $hd.iterator-map (ref null $hd.map))
      (field $hd.iterator-index (mut i32))
      (field $hd.iterator-version i32)))
    (type $hd.map (struct
      (field $hd.map-key-kind i32)
      (field $hd.map-size (mut i32))
      (field $hd.map-keys (mut (ref $hd.list)))
      (field $hd.map-values (mut (ref $hd.list)))
      (field $hd.map-version (mut i32))))
    (type $hd.providers (struct
      (field $hd.provider-key i32)
      (field $hd.provider-value anyref)
      (field $hd.provider-parent (ref null $hd.providers))))
    (type $hd.box-i32 (struct
      (field $hd.box-i32-value i32)))
    (type $hd.box-f64 (struct
      (field $hd.box-f64-value f64)))
    (type $hd.box-extern (struct
      (field $hd.box-extern-value externref)))
    (type $hd.variant (struct
      (field $hd.variant-tag i32)
      (field $hd.variant-payload (mut anyref))))
    (type $closure0 (struct
      (field $closure0fn (ref $sig0))
      (field $closure0env anyref)))
    (type $trait0 (struct
      (field $trait0value anyref)
      (field $trait0bounds (ref null $hd.list))
      (field $trait0m0 (ref $tsig0_0))))
    (type $trait1 (struct
      (field $trait1value anyref)
      (field $trait1bounds (ref null $hd.list))
      (field $trait1m0 (ref $tsig1_0))))
    (type $trait2 (struct
      (field $trait2value anyref)
      (field $trait2bounds (ref null $hd.list))
      (field $trait2m0 (ref $tsig2_0))))
    (type $trait3 (struct
      (field $trait3value anyref)
      (field $trait3bounds (ref null $hd.list))
      (field $trait3m0 (ref $tsig3_0))))
    (type $trait4 (struct
      (field $trait4value anyref)
      (field $trait4bounds (ref null $hd.list))
      (field $trait4m0 (ref $tsig4_0))))
    (type $s0 (struct
      (field $s0state (mut i32))
      (field $s0polls (mut i32))
      (field $s0a0 i32)
      (field $s0result (mut i32))))
    (type $s1 (struct
      (field $s1state (mut i32))
      (field $s1polls (mut i32))
      (field $s1a0 i32)
      (field $s1l1 (mut i32))
      (field $s1l2 (mut i32))
      (field $s1l3 (mut i32))
      (field $s1l4 (mut i32))
      (field $s1l5 (mut i32))
      (field $s1l6 (mut i32))
      (field $s1child0 (mut (ref null $s0)))
      (field $s1result (mut i32))))
    (type $s2 (struct
      (field $s2state (mut i32))
      (field $s2polls (mut i32))
      (field $s2a0 i32)
      (field $s2l1 (mut i32))
      (field $s2l2 (mut i32))
      (field $s2l3 (mut i32))
      (field $s2l4 (mut i32))
      (field $s2l5 (mut i32))
      (field $s2l6 (mut i32))
      (field $s2l7 (mut i32))
      (field $s2l8 (mut i32))
      (field $s2l9 (mut i32))
      (field $s2l10 (mut i32))
      (field $s2l11 (mut i32))
      (field $s2l12 (mut i32))
      (field $s2l13 (mut i32))
      (field $s2l14 (mut i32))
      (field $s2child0 (mut (ref null $s0)))
      (field $s2result (mut i32))))
    (type $s3 (struct
      (field $s3state (mut i32))
      (field $s3polls (mut i32))
      (field $s3a0 i32)
      (field $s3l1 (mut (ref null $hd.bytes)))
      (field $s3l2 (mut (ref null $hd.vector)))
      (field $s3l3 (mut (ref null $hd.list)))
      (field $s3l4 (mut i32))
      (field $s3l5 (mut i32))
      (field $s3child0 (mut (ref null $s0)))
      (field $s3child1 (mut (ref null $s0)))
      (field $s3result (mut i32))))
    (type $s4 (struct
      (field $s4state (mut i32))
      (field $s4polls (mut i32))
      (field $s4a0 i32)
      (field $s4l1 (mut i32))
      (field $s4l2 (mut i32))
      (field $s4l3 (mut i32))
      (field $s4l4 (mut i32))
      (field $s4child0 (mut (ref null $s0)))
      (field $s4child1 (mut (ref null $s0)))
      (field $s4result (mut i32))))
    (type $e0 (struct
      (field $e0tag i32)))
    (type $hd.runtime (struct
      (field $status (mut i32))
      (field $scratch (mut (ref null $hd.bytes)))))
  )

(global $e0v0 (ref $e0)
    (struct.new $e0 (i32.const 0)))

(global $e0v1 (ref $e0)
    (struct.new $e0 (i32.const 1)))

(global $e0v2 (ref $e0)
    (struct.new $e0 (i32.const 2)))

(func $body0 (param $l0 i32) (result i32)
    (call $hd.add_i32 (local.get $l0) (i32.const 1))
  )

(func $f0 (param $l0 i32) (result (ref null $s0))
    (call $hd.trace (i32.const 0) (i32.const 0))
    (struct.new $s0 (i32.const 0) (i32.const 0) (local.get $l0) (i32.const 0))
  )

(func $poll0 (param $frame (ref null $s0)) (result i32)
    (call $hd.trace (i32.const 0) (i32.const 1))
    (if (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 1))
      (then (call $hd.trace (i32.const 0) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or
          (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 2))
          (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 3)))
      (then (call $hd.trace (i32.const 0) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s0 $s0polls (local.get $frame)
      (i32.add (struct.get $s0 $s0polls (local.get $frame)) (i32.const 1)))
    (struct.set $s0 $s0state (local.get $frame) (i32.const 1))
    (if (call $hd.pending
          (i32.const 0)
          (struct.get $s0 $s0polls (local.get $frame)))
      (then
        (struct.set $s0 $s0state (local.get $frame) (i32.const 4))
        (call $hd.trace (i32.const 0) (i32.const 6))
        (return (i32.const 0))))
    (struct.set $s0 $s0state (local.get $frame) (i32.const 1))
    (struct.set $s0 $s0result (local.get $frame) (call $body0 (struct.get $s0 $s0a0 (local.get $frame))))
    (struct.set $s0 $s0state (local.get $frame) (i32.const 2))
    (call $hd.trace (i32.const 0) (i32.const 2))
    (i32.const 1)
  )

(func $drive0 (param $frame (ref null $s0)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll0 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s0 $s0result (local.get $frame))
  )

(func $cancel0 (param $frame (ref null $s0))
    (call $hd.trace (i32.const 0) (i32.const 3))
    (if (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 1))
      (then (call $hd.trace (i32.const 0) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or
          (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 0))
          (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 4)))
      (then (struct.set $s0 $s0state (local.get $frame) (i32.const 3))))
  )

(func $fv0 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f0 (local.get $l0)) (ref.func $swpoll0) (ref.func $swcancel0) (ref.func $swresult0))
  )

(func $f1 (param $l0 i32) (result (ref null $s1))
    (call $hd.trace (i32.const 1) (i32.const 0))
    (struct.new $s1 (i32.const 0) (i32.const 0) (local.get $l0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (ref.null $s0) (i32.const 0))
  )

(func $poll1 (param $frame (ref null $s1)) (result i32)
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (local $l5 i32)
    (local $l6 i32)
    (call $hd.trace (i32.const 1) (i32.const 1))
    (local.set $resume-state (struct.get $s1 $s1state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 1) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 2)) (i32.eq (local.get $resume-state) (i32.const 3)))
      (then (call $hd.trace (i32.const 1) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s1 $s1polls (local.get $frame)
      (i32.add (struct.get $s1 $s1polls (local.get $frame)) (i32.const 1)))
    (struct.set $s1 $s1state (local.get $frame) (i32.const 1))
    (if (call $hd.pending (i32.const 1) (struct.get $s1 $s1polls (local.get $frame)))
      (then
        (struct.set $s1 $s1state (local.get $frame)
          (if (result i32) (i32.eq (local.get $resume-state) (i32.const 0))
            (then (i32.const 4))
            (else (local.get $resume-state))))
        (call $hd.trace (i32.const 1) (i32.const 6))
        (return (i32.const 0))))
    (local.set $l0 (struct.get $s1 $s1a0 (local.get $frame)))
    (local.set $l1 (struct.get $s1 $s1l1 (local.get $frame)))
    (local.set $l2 (struct.get $s1 $s1l2 (local.get $frame)))
    (local.set $l3 (struct.get $s1 $s1l3 (local.get $frame)))
    (local.set $l4 (struct.get $s1 $s1l4 (local.get $frame)))
    (local.set $l5 (struct.get $s1 $s1l5 (local.get $frame)))
    (local.set $l6 (struct.get $s1 $s1l6 (local.get $frame)))
    (struct.set $s1 $s1state (local.get $frame) (i32.const 1))
    (if (i32.le_u (local.get $resume-state) (i32.const 4))
      (then
        (local.set $l1 (call $hd.add_i32 (local.get $l0) (i32.const 1)))
        (local.set $l2 (call $hd.mul_i32 (local.get $l1) (i32.const 2)))
        (local.set $l3 (call $hd.add_i32 (local.get $l2) (i32.const 3)))
        (local.set $l4 (call $hd.sub_i32 (local.get $l3) (i32.const 4)))
        (local.set $l5 (call $hd.add_i32 (local.get $l4) (local.get $l1)))
        (struct.set $s1 $s1child0 (local.get $frame) (call $f0 (local.get $l5)))
        (if (i32.eqz (call $poll0 (struct.get $s1 $s1child0 (local.get $frame))))
          (then
            (struct.set $s1 $s1l1 (local.get $frame) (local.get $l1))
            (struct.set $s1 $s1l2 (local.get $frame) (local.get $l2))
            (struct.set $s1 $s1l3 (local.get $frame) (local.get $l3))
            (struct.set $s1 $s1l4 (local.get $frame) (local.get $l4))
            (struct.set $s1 $s1l5 (local.get $frame) (local.get $l5))
            (struct.set $s1 $s1l6 (local.get $frame) (local.get $l6))
            (struct.set $s1 $s1state (local.get $frame) (i32.const 5))
            (call $hd.trace (i32.const 1) (i32.const 6))
            (return (i32.const 0))))
        (local.set $l6 (struct.get $s0 $s0result (struct.get $s1 $s1child0 (local.get $frame))))
        (struct.set $s1 $s1result (local.get $frame) (call $hd.add_i32 (local.get $l6) (i32.const 1)))
        (struct.set $s1 $s1state (local.get $frame) (i32.const 2))
        (call $hd.trace (i32.const 1) (i32.const 2))
        (return (i32.const 1))
      )
      (else
        (if (i32.eq (local.get $resume-state) (i32.const 5))
          (then
            (if (i32.eqz (call $poll0 (struct.get $s1 $s1child0 (local.get $frame))))
              (then
                (struct.set $s1 $s1l1 (local.get $frame) (local.get $l1))
                (struct.set $s1 $s1l2 (local.get $frame) (local.get $l2))
                (struct.set $s1 $s1l3 (local.get $frame) (local.get $l3))
                (struct.set $s1 $s1l4 (local.get $frame) (local.get $l4))
                (struct.set $s1 $s1l5 (local.get $frame) (local.get $l5))
                (struct.set $s1 $s1l6 (local.get $frame) (local.get $l6))
                (struct.set $s1 $s1state (local.get $frame) (i32.const 5))
                (call $hd.trace (i32.const 1) (i32.const 6))
                (return (i32.const 0))))
            (local.set $l6 (struct.get $s0 $s0result (struct.get $s1 $s1child0 (local.get $frame))))
            (struct.set $s1 $s1result (local.get $frame) (call $hd.add_i32 (local.get $l6) (i32.const 1)))
            (struct.set $s1 $s1state (local.get $frame) (i32.const 2))
            (call $hd.trace (i32.const 1) (i32.const 2))
            (return (i32.const 1))
          )
          (else
            (unreachable)
          ))
      ))
  )

(func $drive1 (param $frame (ref null $s1)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll1 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s1 $s1result (local.get $frame))
  )

(func $cancel1 (param $frame (ref null $s1))
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (local $l5 i32)
    (local $l6 i32)
    (call $hd.trace (i32.const 1) (i32.const 3))
    (local.set $resume-state (struct.get $s1 $s1state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 1) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (local.set $l0 (struct.get $s1 $s1a0 (local.get $frame)))
    (local.set $l1 (struct.get $s1 $s1l1 (local.get $frame)))
    (local.set $l2 (struct.get $s1 $s1l2 (local.get $frame)))
    (local.set $l3 (struct.get $s1 $s1l3 (local.get $frame)))
    (local.set $l4 (struct.get $s1 $s1l4 (local.get $frame)))
    (local.set $l5 (struct.get $s1 $s1l5 (local.get $frame)))
    (local.set $l6 (struct.get $s1 $s1l6 (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 5))
      (then
        (call $cancel0 (struct.get $s1 $s1child0 (local.get $frame)))
        (struct.set $s1 $s1state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 0)) (i32.eq (local.get $resume-state) (i32.const 4)))
      (then (struct.set $s1 $s1state (local.get $frame) (i32.const 3))))
  )

(func $fv1 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f1 (local.get $l0)) (ref.func $swpoll1) (ref.func $swcancel1) (ref.func $swresult1))
  )

(func $f2 (param $l0 i32) (result (ref null $s2))
    (call $hd.trace (i32.const 2) (i32.const 0))
    (struct.new $s2 (i32.const 0) (i32.const 0) (local.get $l0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (ref.null $s0) (i32.const 0))
  )

(func $poll2 (param $frame (ref null $s2)) (result i32)
    (local $resume-state i32)
    (local $pc i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (local $l5 i32)
    (local $l6 i32)
    (local $l7 i32)
    (local $l8 i32)
    (local $l9 i32)
    (local $l10 i32)
    (local $l11 i32)
    (local $l12 i32)
    (local $l13 i32)
    (local $l14 i32)
    (local $tmp0 i32)
    (call $hd.trace (i32.const 2) (i32.const 1))
    (local.set $resume-state (struct.get $s2 $s2state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 2) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 2)) (i32.eq (local.get $resume-state) (i32.const 3)))
      (then (call $hd.trace (i32.const 2) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s2 $s2polls (local.get $frame)
      (i32.add (struct.get $s2 $s2polls (local.get $frame)) (i32.const 1)))
    (struct.set $s2 $s2state (local.get $frame) (i32.const 1))
    (if (call $hd.pending (i32.const 2) (struct.get $s2 $s2polls (local.get $frame)))
      (then
        (struct.set $s2 $s2state (local.get $frame)
          (if (result i32) (i32.eq (local.get $resume-state) (i32.const 0))
            (then (i32.const 4))
            (else (local.get $resume-state))))
        (call $hd.trace (i32.const 2) (i32.const 6))
        (return (i32.const 0))))
    (local.set $l0 (struct.get $s2 $s2a0 (local.get $frame)))
    (local.set $l1 (struct.get $s2 $s2l1 (local.get $frame)))
    (local.set $l2 (struct.get $s2 $s2l2 (local.get $frame)))
    (local.set $l3 (struct.get $s2 $s2l3 (local.get $frame)))
    (local.set $l4 (struct.get $s2 $s2l4 (local.get $frame)))
    (local.set $l5 (struct.get $s2 $s2l5 (local.get $frame)))
    (local.set $l6 (struct.get $s2 $s2l6 (local.get $frame)))
    (local.set $l7 (struct.get $s2 $s2l7 (local.get $frame)))
    (local.set $l8 (struct.get $s2 $s2l8 (local.get $frame)))
    (local.set $l9 (struct.get $s2 $s2l9 (local.get $frame)))
    (local.set $l10 (struct.get $s2 $s2l10 (local.get $frame)))
    (local.set $l11 (struct.get $s2 $s2l11 (local.get $frame)))
    (local.set $l12 (struct.get $s2 $s2l12 (local.get $frame)))
    (local.set $l13 (struct.get $s2 $s2l13 (local.get $frame)))
    (local.set $l14 (struct.get $s2 $s2l14 (local.get $frame)))
    (struct.set $s2 $s2state (local.get $frame) (i32.const 1))
    (if (i32.le_u (local.get $resume-state) (i32.const 4))
      (then (local.set $pc (i32.const 19)))
      (else
        (if (i32.eq (local.get $resume-state) (i32.const 5))
          (then
            (if (i32.eqz (call $poll0 (struct.get $s2 $s2child0 (local.get $frame))))
              (then
                (struct.set $s2 $s2l1 (local.get $frame) (local.get $l1))
                (struct.set $s2 $s2l2 (local.get $frame) (local.get $l2))
                (struct.set $s2 $s2l3 (local.get $frame) (local.get $l3))
                (struct.set $s2 $s2l4 (local.get $frame) (local.get $l4))
                (struct.set $s2 $s2l5 (local.get $frame) (local.get $l5))
                (struct.set $s2 $s2l6 (local.get $frame) (local.get $l6))
                (struct.set $s2 $s2l7 (local.get $frame) (local.get $l7))
                (struct.set $s2 $s2l8 (local.get $frame) (local.get $l8))
                (struct.set $s2 $s2l9 (local.get $frame) (local.get $l9))
                (struct.set $s2 $s2l10 (local.get $frame) (local.get $l10))
                (struct.set $s2 $s2l11 (local.get $frame) (local.get $l11))
                (struct.set $s2 $s2l12 (local.get $frame) (local.get $l12))
                (struct.set $s2 $s2l13 (local.get $frame) (local.get $l13))
                (struct.set $s2 $s2l14 (local.get $frame) (local.get $l14))
                (struct.set $s2 $s2state (local.get $frame) (local.get $resume-state))
                (call $hd.trace (i32.const 2) (i32.const 6))
                (return (i32.const 0))))
            (local.set $l9 (struct.get $s0 $s0result (struct.get $s2 $s2child0 (local.get $frame))))
            (local.set $pc (i32.const 8))
          )
          (else
            (local.set $pc (i32.const 19))
          ))
      ))
    (loop $cfg
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (local.set $l4 (local.get $l1))
          (struct.set $s2 $s2result (local.get $frame) (local.get $l4))
          (struct.set $s2 $s2state (local.get $frame) (i32.const 2))
          (call $hd.trace (i32.const 2) (i32.const 2))
          (return (i32.const 1))
        ))
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $pc (i32.const 0))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $pc (i32.const 17))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $pc (i32.const 2))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $l2 (call $hd.add_i32 (local.get $l11) (local.get $l12)))
          (local.set $pc (i32.const 3))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $l12 (i32.const 1))
          (local.set $pc (i32.const 4))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $l11 (local.get $l2))
          (local.set $pc (i32.const 5))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $l1 (call $hd.add_i32 (local.get $l7) (local.get $l10)))
          (local.set $pc (i32.const 6))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (local.set $l10 (local.get $l9))
          (local.set $pc (i32.const 7))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (struct.set $s2 $s2child0 (local.get $frame) (call $f0 (local.get $l8)))
          (if (i32.eqz (call $poll0 (struct.get $s2 $s2child0 (local.get $frame))))
            (then
              (struct.set $s2 $s2l1 (local.get $frame) (local.get $l1))
              (struct.set $s2 $s2l2 (local.get $frame) (local.get $l2))
              (struct.set $s2 $s2l3 (local.get $frame) (local.get $l3))
              (struct.set $s2 $s2l4 (local.get $frame) (local.get $l4))
              (struct.set $s2 $s2l5 (local.get $frame) (local.get $l5))
              (struct.set $s2 $s2l6 (local.get $frame) (local.get $l6))
              (struct.set $s2 $s2l7 (local.get $frame) (local.get $l7))
              (struct.set $s2 $s2l8 (local.get $frame) (local.get $l8))
              (struct.set $s2 $s2l9 (local.get $frame) (local.get $l9))
              (struct.set $s2 $s2l10 (local.get $frame) (local.get $l10))
              (struct.set $s2 $s2l11 (local.get $frame) (local.get $l11))
              (struct.set $s2 $s2l12 (local.get $frame) (local.get $l12))
              (struct.set $s2 $s2l13 (local.get $frame) (local.get $l13))
              (struct.set $s2 $s2l14 (local.get $frame) (local.get $l14))
              (struct.set $s2 $s2state (local.get $frame) (i32.const 5))
              (call $hd.trace (i32.const 2) (i32.const 6))
              (return (i32.const 0))))
          (local.set $l9 (struct.get $s0 $s0result (struct.get $s2 $s2child0 (local.get $frame))))
          (local.set $pc (i32.const 8))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (local.set $l8 (local.get $l3))
          (local.set $pc (i32.const 9))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 11))
        (then
          (local.set $l7 (local.get $l1))
          (local.set $pc (i32.const 10))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 12))
        (then
          (local.set $l3 (call $hd.mul_i32 (local.get $l5) (local.get $l6)))
          (local.set $pc (i32.const 11))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 13))
        (then
          (local.set $l6 (i32.const 2))
          (local.set $pc (i32.const 12))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 14))
        (then
          (local.set $l5 (local.get $l2))
          (local.set $pc (i32.const 13))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 15))
        (then
          (if (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l13) (local.get $l14)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l13) (local.get $l14)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))
            (then (local.set $pc (i32.const 14)))
            (else (local.set $pc (i32.const 1))))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 16))
        (then
          (local.set $l14 (local.get $l0))
          (local.set $pc (i32.const 15))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 17))
        (then
          (local.set $l13 (local.get $l2))
          (local.set $pc (i32.const 16))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 18))
        (then
          (local.set $l2 (i32.const 0))
          (local.set $pc (i32.const 2))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 19))
        (then
          (local.set $l1 (i32.const 0))
          (local.set $pc (i32.const 18))
          (br $cfg)
        ))
      unreachable
    )
  )

(func $drive2 (param $frame (ref null $s2)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll2 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s2 $s2result (local.get $frame))
  )

(func $cancel2 (param $frame (ref null $s2))
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (local $l5 i32)
    (local $l6 i32)
    (local $l7 i32)
    (local $l8 i32)
    (local $l9 i32)
    (local $l10 i32)
    (local $l11 i32)
    (local $l12 i32)
    (local $l13 i32)
    (local $l14 i32)
    (local $tmp0 i32)
    (call $hd.trace (i32.const 2) (i32.const 3))
    (local.set $resume-state (struct.get $s2 $s2state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 2) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (local.set $l0 (struct.get $s2 $s2a0 (local.get $frame)))
    (local.set $l1 (struct.get $s2 $s2l1 (local.get $frame)))
    (local.set $l2 (struct.get $s2 $s2l2 (local.get $frame)))
    (local.set $l3 (struct.get $s2 $s2l3 (local.get $frame)))
    (local.set $l4 (struct.get $s2 $s2l4 (local.get $frame)))
    (local.set $l5 (struct.get $s2 $s2l5 (local.get $frame)))
    (local.set $l6 (struct.get $s2 $s2l6 (local.get $frame)))
    (local.set $l7 (struct.get $s2 $s2l7 (local.get $frame)))
    (local.set $l8 (struct.get $s2 $s2l8 (local.get $frame)))
    (local.set $l9 (struct.get $s2 $s2l9 (local.get $frame)))
    (local.set $l10 (struct.get $s2 $s2l10 (local.get $frame)))
    (local.set $l11 (struct.get $s2 $s2l11 (local.get $frame)))
    (local.set $l12 (struct.get $s2 $s2l12 (local.get $frame)))
    (local.set $l13 (struct.get $s2 $s2l13 (local.get $frame)))
    (local.set $l14 (struct.get $s2 $s2l14 (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 5))
      (then
        (call $cancel0 (struct.get $s2 $s2child0 (local.get $frame)))
        (struct.set $s2 $s2state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 0)) (i32.eq (local.get $resume-state) (i32.const 4)))
      (then (struct.set $s2 $s2state (local.get $frame) (i32.const 3))))
  )

(func $fv2 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f2 (local.get $l0)) (ref.func $swpoll2) (ref.func $swcancel2) (ref.func $swresult2))
  )

(func $f3 (param $l0 i32) (result (ref null $s3))
    (call $hd.trace (i32.const 3) (i32.const 0))
    (struct.new $s3 (i32.const 0) (i32.const 0) (local.get $l0) (ref.null $hd.bytes) (ref.null $hd.vector) (ref.null $hd.list) (i32.const 0) (i32.const 0) (ref.null $s0) (ref.null $s0) (i32.const 0))
  )

(func $poll3 (param $frame (ref null $s3)) (result i32)
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 (ref null $hd.bytes))
    (local $l2 (ref null $hd.vector))
    (local $l3 (ref null $hd.list))
    (local $l4 i32)
    (local $l5 i32)
    (call $hd.trace (i32.const 3) (i32.const 1))
    (local.set $resume-state (struct.get $s3 $s3state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 3) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 2)) (i32.eq (local.get $resume-state) (i32.const 3)))
      (then (call $hd.trace (i32.const 3) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s3 $s3polls (local.get $frame)
      (i32.add (struct.get $s3 $s3polls (local.get $frame)) (i32.const 1)))
    (struct.set $s3 $s3state (local.get $frame) (i32.const 1))
    (if (call $hd.pending (i32.const 3) (struct.get $s3 $s3polls (local.get $frame)))
      (then
        (struct.set $s3 $s3state (local.get $frame)
          (if (result i32) (i32.eq (local.get $resume-state) (i32.const 0))
            (then (i32.const 4))
            (else (local.get $resume-state))))
        (call $hd.trace (i32.const 3) (i32.const 6))
        (return (i32.const 0))))
    (local.set $l0 (struct.get $s3 $s3a0 (local.get $frame)))
    (local.set $l1 (struct.get $s3 $s3l1 (local.get $frame)))
    (local.set $l2 (struct.get $s3 $s3l2 (local.get $frame)))
    (local.set $l3 (struct.get $s3 $s3l3 (local.get $frame)))
    (local.set $l4 (struct.get $s3 $s3l4 (local.get $frame)))
    (local.set $l5 (struct.get $s3 $s3l5 (local.get $frame)))
    (struct.set $s3 $s3state (local.get $frame) (i32.const 1))
    (if (i32.le_u (local.get $resume-state) (i32.const 4))
      (then
        (local.set $l1 (array.new_fixed $hd.bytes 3 (i32.const 97) (i32.const 98) (i32.const 99)))
        (local.set $l2 (struct.new $hd.vector (i32.const 3) (array.new_fixed $hd.list 3 (struct.new $hd.box-i32 (local.get $l0)) (struct.new $hd.box-i32 (local.get $l0)) (struct.new $hd.box-i32 (local.get $l0))) (i32.const 0)))
        (local.set $l3 (array.new_fixed $hd.list 2 (struct.new $hd.box-i32 (local.get $l0)) (local.get $l1)))
        (struct.set $s3 $s3child0 (local.get $frame) (call $f0 (call $hd.add_i32 (call $hd.add_i32 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l2)) (i32.const 0)))) (call $hd.string_len (local.get $l1))) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (array.get $hd.list (ref.as_non_null (local.get $l3)) (i32.const 0)))))))
        (if (i32.eqz (call $poll0 (struct.get $s3 $s3child0 (local.get $frame))))
          (then
            (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
            (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
            (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
            (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
            (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
            (struct.set $s3 $s3state (local.get $frame) (i32.const 5))
            (call $hd.trace (i32.const 3) (i32.const 6))
            (return (i32.const 0))))
        (local.set $l4 (struct.get $s0 $s0result (struct.get $s3 $s3child0 (local.get $frame))))
        (struct.set $s3 $s3child1 (local.get $frame) (call $f0 (local.get $l4)))
        (if (i32.eqz (call $poll0 (struct.get $s3 $s3child1 (local.get $frame))))
          (then
            (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
            (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
            (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
            (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
            (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
            (struct.set $s3 $s3state (local.get $frame) (i32.const 6))
            (call $hd.trace (i32.const 3) (i32.const 6))
            (return (i32.const 0))))
        (local.set $l5 (struct.get $s0 $s0result (struct.get $s3 $s3child1 (local.get $frame))))
        (struct.set $s3 $s3result (local.get $frame) (local.get $l5))
        (struct.set $s3 $s3state (local.get $frame) (i32.const 2))
        (call $hd.trace (i32.const 3) (i32.const 2))
        (return (i32.const 1))
      )
      (else
        (if (i32.eq (local.get $resume-state) (i32.const 5))
          (then
            (if (i32.eqz (call $poll0 (struct.get $s3 $s3child0 (local.get $frame))))
              (then
                (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
                (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
                (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
                (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
                (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
                (struct.set $s3 $s3state (local.get $frame) (i32.const 5))
                (call $hd.trace (i32.const 3) (i32.const 6))
                (return (i32.const 0))))
            (local.set $l4 (struct.get $s0 $s0result (struct.get $s3 $s3child0 (local.get $frame))))
            (struct.set $s3 $s3child1 (local.get $frame) (call $f0 (local.get $l4)))
            (if (i32.eqz (call $poll0 (struct.get $s3 $s3child1 (local.get $frame))))
              (then
                (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
                (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
                (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
                (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
                (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
                (struct.set $s3 $s3state (local.get $frame) (i32.const 6))
                (call $hd.trace (i32.const 3) (i32.const 6))
                (return (i32.const 0))))
            (local.set $l5 (struct.get $s0 $s0result (struct.get $s3 $s3child1 (local.get $frame))))
            (struct.set $s3 $s3result (local.get $frame) (local.get $l5))
            (struct.set $s3 $s3state (local.get $frame) (i32.const 2))
            (call $hd.trace (i32.const 3) (i32.const 2))
            (return (i32.const 1))
          )
          (else
            (if (i32.eq (local.get $resume-state) (i32.const 6))
              (then
                (if (i32.eqz (call $poll0 (struct.get $s3 $s3child1 (local.get $frame))))
                  (then
                    (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
                    (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
                    (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
                    (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
                    (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
                    (struct.set $s3 $s3state (local.get $frame) (i32.const 6))
                    (call $hd.trace (i32.const 3) (i32.const 6))
                    (return (i32.const 0))))
                (local.set $l5 (struct.get $s0 $s0result (struct.get $s3 $s3child1 (local.get $frame))))
                (struct.set $s3 $s3result (local.get $frame) (local.get $l5))
                (struct.set $s3 $s3state (local.get $frame) (i32.const 2))
                (call $hd.trace (i32.const 3) (i32.const 2))
                (return (i32.const 1))
              )
              (else
                (unreachable)
              ))
          ))
      ))
  )

(func $drive3 (param $frame (ref null $s3)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll3 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s3 $s3result (local.get $frame))
  )

(func $cancel3 (param $frame (ref null $s3))
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 (ref null $hd.bytes))
    (local $l2 (ref null $hd.vector))
    (local $l3 (ref null $hd.list))
    (local $l4 i32)
    (local $l5 i32)
    (call $hd.trace (i32.const 3) (i32.const 3))
    (local.set $resume-state (struct.get $s3 $s3state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 3) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (local.set $l0 (struct.get $s3 $s3a0 (local.get $frame)))
    (local.set $l1 (struct.get $s3 $s3l1 (local.get $frame)))
    (local.set $l2 (struct.get $s3 $s3l2 (local.get $frame)))
    (local.set $l3 (struct.get $s3 $s3l3 (local.get $frame)))
    (local.set $l4 (struct.get $s3 $s3l4 (local.get $frame)))
    (local.set $l5 (struct.get $s3 $s3l5 (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 5))
      (then
        (call $cancel0 (struct.get $s3 $s3child0 (local.get $frame)))
        (struct.set $s3 $s3state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.eq (local.get $resume-state) (i32.const 6))
      (then
        (call $cancel0 (struct.get $s3 $s3child1 (local.get $frame)))
        (struct.set $s3 $s3state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 0)) (i32.eq (local.get $resume-state) (i32.const 4)))
      (then (struct.set $s3 $s3state (local.get $frame) (i32.const 3))))
  )

(func $fv3 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f3 (local.get $l0)) (ref.func $swpoll3) (ref.func $swcancel3) (ref.func $swresult3))
  )

(func $f4 (param $l0 i32) (result (ref null $s4))
    (call $hd.trace (i32.const 4) (i32.const 0))
    (struct.new $s4 (i32.const 0) (i32.const 0) (local.get $l0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (ref.null $s0) (ref.null $s0) (i32.const 0))
  )

(func $poll4 (param $frame (ref null $s4)) (result i32)
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (call $hd.trace (i32.const 4) (i32.const 1))
    (local.set $resume-state (struct.get $s4 $s4state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 4) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 2)) (i32.eq (local.get $resume-state) (i32.const 3)))
      (then (call $hd.trace (i32.const 4) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s4 $s4polls (local.get $frame)
      (i32.add (struct.get $s4 $s4polls (local.get $frame)) (i32.const 1)))
    (struct.set $s4 $s4state (local.get $frame) (i32.const 1))
    (if (call $hd.pending (i32.const 4) (struct.get $s4 $s4polls (local.get $frame)))
      (then
        (struct.set $s4 $s4state (local.get $frame)
          (if (result i32) (i32.eq (local.get $resume-state) (i32.const 0))
            (then (i32.const 4))
            (else (local.get $resume-state))))
        (call $hd.trace (i32.const 4) (i32.const 6))
        (return (i32.const 0))))
    (local.set $l0 (struct.get $s4 $s4a0 (local.get $frame)))
    (local.set $l1 (struct.get $s4 $s4l1 (local.get $frame)))
    (local.set $l2 (struct.get $s4 $s4l2 (local.get $frame)))
    (local.set $l3 (struct.get $s4 $s4l3 (local.get $frame)))
    (local.set $l4 (struct.get $s4 $s4l4 (local.get $frame)))
    (struct.set $s4 $s4state (local.get $frame) (i32.const 1))
    (if (i32.le_u (local.get $resume-state) (i32.const 4))
      (then
        (local.set $l1 (call $hd.mul_i32 (local.get $l0) (i32.const 3)))
        (struct.set $s4 $s4child0 (local.get $frame) (call $f0 (local.get $l1)))
        (if (i32.eqz (call $poll0 (struct.get $s4 $s4child0 (local.get $frame))))
          (then
            (struct.set $s4 $s4l1 (local.get $frame) (local.get $l1))
            (struct.set $s4 $s4l2 (local.get $frame) (local.get $l2))
            (struct.set $s4 $s4l3 (local.get $frame) (local.get $l3))
            (struct.set $s4 $s4l4 (local.get $frame) (local.get $l4))
            (struct.set $s4 $s4state (local.get $frame) (i32.const 5))
            (call $hd.trace (i32.const 4) (i32.const 6))
            (return (i32.const 0))))
        (local.set $l2 (struct.get $s0 $s0result (struct.get $s4 $s4child0 (local.get $frame))))
        (local.set $l3 (call $hd.add_i32 (local.get $l2) (local.get $l1)))
        (struct.set $s4 $s4child1 (local.get $frame) (call $f0 (local.get $l3)))
        (if (i32.eqz (call $poll0 (struct.get $s4 $s4child1 (local.get $frame))))
          (then
            (struct.set $s4 $s4l1 (local.get $frame) (local.get $l1))
            (struct.set $s4 $s4l2 (local.get $frame) (local.get $l2))
            (struct.set $s4 $s4l3 (local.get $frame) (local.get $l3))
            (struct.set $s4 $s4l4 (local.get $frame) (local.get $l4))
            (struct.set $s4 $s4state (local.get $frame) (i32.const 6))
            (call $hd.trace (i32.const 4) (i32.const 6))
            (return (i32.const 0))))
        (local.set $l4 (struct.get $s0 $s0result (struct.get $s4 $s4child1 (local.get $frame))))
        (struct.set $s4 $s4result (local.get $frame) (local.get $l4))
        (struct.set $s4 $s4state (local.get $frame) (i32.const 2))
        (call $hd.trace (i32.const 4) (i32.const 2))
        (return (i32.const 1))
      )
      (else
        (if (i32.eq (local.get $resume-state) (i32.const 5))
          (then
            (if (i32.eqz (call $poll0 (struct.get $s4 $s4child0 (local.get $frame))))
              (then
                (struct.set $s4 $s4l1 (local.get $frame) (local.get $l1))
                (struct.set $s4 $s4l2 (local.get $frame) (local.get $l2))
                (struct.set $s4 $s4l3 (local.get $frame) (local.get $l3))
                (struct.set $s4 $s4l4 (local.get $frame) (local.get $l4))
                (struct.set $s4 $s4state (local.get $frame) (i32.const 5))
                (call $hd.trace (i32.const 4) (i32.const 6))
                (return (i32.const 0))))
            (local.set $l2 (struct.get $s0 $s0result (struct.get $s4 $s4child0 (local.get $frame))))
            (local.set $l3 (call $hd.add_i32 (local.get $l2) (local.get $l1)))
            (struct.set $s4 $s4child1 (local.get $frame) (call $f0 (local.get $l3)))
            (if (i32.eqz (call $poll0 (struct.get $s4 $s4child1 (local.get $frame))))
              (then
                (struct.set $s4 $s4l1 (local.get $frame) (local.get $l1))
                (struct.set $s4 $s4l2 (local.get $frame) (local.get $l2))
                (struct.set $s4 $s4l3 (local.get $frame) (local.get $l3))
                (struct.set $s4 $s4l4 (local.get $frame) (local.get $l4))
                (struct.set $s4 $s4state (local.get $frame) (i32.const 6))
                (call $hd.trace (i32.const 4) (i32.const 6))
                (return (i32.const 0))))
            (local.set $l4 (struct.get $s0 $s0result (struct.get $s4 $s4child1 (local.get $frame))))
            (struct.set $s4 $s4result (local.get $frame) (local.get $l4))
            (struct.set $s4 $s4state (local.get $frame) (i32.const 2))
            (call $hd.trace (i32.const 4) (i32.const 2))
            (return (i32.const 1))
          )
          (else
            (if (i32.eq (local.get $resume-state) (i32.const 6))
              (then
                (if (i32.eqz (call $poll0 (struct.get $s4 $s4child1 (local.get $frame))))
                  (then
                    (struct.set $s4 $s4l1 (local.get $frame) (local.get $l1))
                    (struct.set $s4 $s4l2 (local.get $frame) (local.get $l2))
                    (struct.set $s4 $s4l3 (local.get $frame) (local.get $l3))
                    (struct.set $s4 $s4l4 (local.get $frame) (local.get $l4))
                    (struct.set $s4 $s4state (local.get $frame) (i32.const 6))
                    (call $hd.trace (i32.const 4) (i32.const 6))
                    (return (i32.const 0))))
                (local.set $l4 (struct.get $s0 $s0result (struct.get $s4 $s4child1 (local.get $frame))))
                (struct.set $s4 $s4result (local.get $frame) (local.get $l4))
                (struct.set $s4 $s4state (local.get $frame) (i32.const 2))
                (call $hd.trace (i32.const 4) (i32.const 2))
                (return (i32.const 1))
              )
              (else
                (unreachable)
              ))
          ))
      ))
  )

(func $drive4 (param $frame (ref null $s4)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll4 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s4 $s4result (local.get $frame))
  )

(func $cancel4 (param $frame (ref null $s4))
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (call $hd.trace (i32.const 4) (i32.const 3))
    (local.set $resume-state (struct.get $s4 $s4state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 4) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (local.set $l0 (struct.get $s4 $s4a0 (local.get $frame)))
    (local.set $l1 (struct.get $s4 $s4l1 (local.get $frame)))
    (local.set $l2 (struct.get $s4 $s4l2 (local.get $frame)))
    (local.set $l3 (struct.get $s4 $s4l3 (local.get $frame)))
    (local.set $l4 (struct.get $s4 $s4l4 (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 5))
      (then
        (call $cancel0 (struct.get $s4 $s4child0 (local.get $frame)))
        (struct.set $s4 $s4state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.eq (local.get $resume-state) (i32.const 6))
      (then
        (call $cancel0 (struct.get $s4 $s4child1 (local.get $frame)))
        (struct.set $s4 $s4state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 0)) (i32.eq (local.get $resume-state) (i32.const 4)))
      (then (struct.set $s4 $s4state (local.get $frame) (i32.const 3))))
  )

(func $fv4 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f4 (local.get $l0)) (ref.func $swpoll4) (ref.func $swcancel4) (ref.func $swresult4))
  )

(func $swpoll0 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll0 (ref.cast (ref $s0) (local.get $inner))))

(func $swcancel0 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel0 (ref.cast (ref $s0) (local.get $inner))))

(func $swresult0 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s0 $s0result (ref.cast (ref $s0) (local.get $inner)))))

(func $swpoll1 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll1 (ref.cast (ref $s1) (local.get $inner))))

(func $swcancel1 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel1 (ref.cast (ref $s1) (local.get $inner))))

(func $swresult1 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s1 $s1result (ref.cast (ref $s1) (local.get $inner)))))

(func $swpoll2 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll2 (ref.cast (ref $s2) (local.get $inner))))

(func $swcancel2 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel2 (ref.cast (ref $s2) (local.get $inner))))

(func $swresult2 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s2 $s2result (ref.cast (ref $s2) (local.get $inner)))))

(func $swpoll3 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll3 (ref.cast (ref $s3) (local.get $inner))))

(func $swcancel3 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel3 (ref.cast (ref $s3) (local.get $inner))))

(func $swresult3 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s3 $s3result (ref.cast (ref $s3) (local.get $inner)))))

(func $swpoll4 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll4 (ref.cast (ref $s4) (local.get $inner))))

(func $swcancel4 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel4 (ref.cast (ref $s4) (local.get $inner))))

(func $swresult4 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s4 $s4result (ref.cast (ref $s4) (local.get $inner)))))
