;; commit bd985d7; command: erasure-excerpts.ts (emitWat of audit/probes/arch/erasure/erasure-bench.hd); date: 2026-09-25T20:54:17.628Z
(rec
    (type $sig0 (func (param anyref) (param (ref null $hd.vector)) (result i32)))
    (type $sig1 (func (param anyref) (param (ref null $hd.vector)) (result f64)))
    (type $sig2 (func (param anyref) (param (ref null $hd.vector)) (result i32)))
    (type $sig3 (func (param anyref) (param i32) (result (ref null $hd.vector))))
    (type $sig4 (func (param anyref) (param i32) (result (ref null $hd.vector))))
    (type $sig5 (func (param anyref) (param i32) (param i32) (result i32)))
    (type $sig6 (func (param anyref) (param i32) (param i32) (result f64)))
    (type $sig7 (func (param anyref) (result i32)))
    (type $sig8 (func (param anyref) (param i32) (result i32)))
    (type $sig9 (func (param anyref) (param f64) (param f64) (result f64)))
    (type $sig10 (func (param anyref) (param f64) (result f64)))
    (type $sig11 (func (param anyref) (param i32) (param i32) (result i32)))
    (type $tsig0_0 (func (param anyref) (param anyref) (param anyref) (result anyref)))
    (type $tsig0_1 (func (param anyref) (param anyref) (result anyref)))
    (type $tsig1_0 (func (param anyref) (param anyref) (param anyref) (result i32)))
    (type $tsig2_0 (func (param anyref) (param anyref) (result (ref null $hd.bytes))))
    (type $tsig3_0 (func (param anyref) (param anyref) (param anyref) (result i32)))
    (type $tsig4_0 (func (param anyref) (param anyref) (param anyref) (result (ref null $hd.variant))))
    (type $tsig5_0 (func (param anyref) (param anyref)))
    (type $tsig6_0 (func (param anyref) (param anyref) (result (ref null $hd.variant))))
    (type $hd.suspension-poll-sig (func (param anyref) (result i32)))
    (type $hd.suspension-cancel-sig (func (param anyref)))
    (type $hd.suspension-result-sig (func (param anyref) (result anyref)))
    (type $hd.suspension (struct
      (field $hd.suspension-inner anyref)
      (field $hd.suspension-poll (ref $hd.suspension-poll-sig))
      (field $hd.suspension-cancel (ref $hd.suspension-cancel-sig))
      (field $hd.suspension-result (ref $hd.suspension-result-sig))))
    (type $hd.bytes (array (mut i8)))
    (type $hd.list (array (mut anyref)))
    (type $hd.vector (struct
      (field $hd.vector-size (mut i32))
      (field $hd.vector-values (mut (ref $hd.list)))
      (field $hd.vector-version (mut i32))))
    (type $hd.iterator (struct
      (field $hd.iterator-list (ref null $hd.vector))
      (field $hd.iterator-map (ref null $hd.map))
      (field $hd.iterator-index (mut i32))
      (field $hd.iterator-version i32)))
    (type $hd.map (struct
      (field $hd.map-key-kind i32)
      (field $hd.map-size (mut i32))
      (field $hd.map-keys (mut (ref $hd.list)))
      (field $hd.map-values (mut (ref $hd.list)))
      (field $hd.map-version (mut i32))))
    (type $hd.providers (struct
      (field $hd.provider-key i32)
      (field $hd.provider-value anyref)
      (field $hd.provider-parent (ref null $hd.providers))))
    (type $hd.box-i32 (struct
      (field $hd.box-i32-value i32)))
    (type $hd.box-f64 (struct
      (field $hd.box-f64-value f64)))
    (type $hd.box-extern (struct
      (field $hd.box-extern-value externref)))
    (type $hd.variant (struct
      (field $hd.variant-tag i32)
      (field $hd.variant-payload (mut anyref))))
    (type $closure0 (struct
      (field $closure0fn (ref $sig0))
      (field $closure0env anyref)))
    (type $closure1 (struct
      (field $closure1fn (ref $sig1))
      (field $closure1env anyref)))
    (type $closure2 (struct
      (field $closure2fn (ref $sig2))
      (field $closure2env anyref)))
    (type $closure3 (struct
      (field $closure3fn (ref $sig3))
      (field $closure3env anyref)))
    (type $closure4 (struct
      (field $closure4fn (ref $sig4))
      (field $closure4env anyref)))
    (type $closure5 (struct
      (field $closure5fn (ref $sig5))
      (field $closure5env anyref)))
    (type $closure6 (struct
      (field $closure6fn (ref $sig6))
      (field $closure6env anyref)))
    (type $closure7 (struct
      (field $closure7fn (ref $sig7))
      (field $closure7env anyref)))
    (type $closure8 (struct
      (field $closure8fn (ref $sig8))
      (field $closure8env anyref)))
    (type $closure9 (struct
      (field $closure9fn (ref $sig9))
      (field $closure9env anyref)))
    (type $closure10 (struct
      (field $closure10fn (ref $sig10))
      (field $closure10env anyref)))
    (type $closure11 (struct
      (field $closure11fn (ref $sig11))
      (field $closure11env anyref)))
    (type $trait0 (struct
      (field $trait0value anyref)
      (field $trait0bounds (ref null $hd.list))
      (field $trait0m0 (ref $tsig0_0))
      (field $trait0m1 (ref $tsig0_1))))
    (type $trait1 (struct
      (field $trait1value anyref)
      (field $trait1bounds (ref null $hd.list))
      (field $trait1m0 (ref $tsig1_0))))
    (type $trait2 (struct
      (field $trait2value anyref)
      (field $trait2bounds (ref null $hd.list))
      (field $trait2m0 (ref $tsig2_0))))
    (type $trait3 (struct
      (field $trait3value anyref)
      (field $trait3bounds (ref null $hd.list))
      (field $trait3m0 (ref $tsig3_0))))
    (type $trait4 (struct
      (field $trait4value anyref)
      (field $trait4bounds (ref null $hd.list))
      (field $trait4m0 (ref $tsig4_0))))
    (type $trait5 (struct
      (field $trait5value anyref)
      (field $trait5bounds (ref null $hd.list))
      (field $trait5m0 (ref $tsig5_0))))
    (type $trait6 (struct
      (field $trait6value anyref)
      (field $trait6bounds (ref null $hd.list))
      (field $trait6m0 (ref $tsig6_0))))
    (type $e0 (struct
      (field $e0tag i32)))
    (type $hd.runtime (struct
      (field $status (mut i32))
      (field $scratch (mut (ref null $hd.bytes)))))
  )

(global $e0v0 (ref $e0)
    (struct.new $e0 (i32.const 0)))

(global $e0v1 (ref $e0)
    (struct.new $e0 (i32.const 1)))

(global $e0v2 (ref $e0)
    (struct.new $e0 (i32.const 2)))

(func $f0 (param $l0 (ref null $hd.vector)) (param $l1 anyref) (param $bound0 (ref null $trait0)) (result anyref)
    (local $l2 anyref)
    (local $l3 anyref)
    (local $tmp0 (ref null $trait0))
    (local $tmp1 (ref null $hd.iterator))
    (local $tmp2 (ref null $hd.variant))
    (local $tmp3 anyref)
    (local $tmp4 (ref null $hd.vector))
    (local $tmp5 (ref null $hd.iterator))
    (local $tmp6 (ref null $hd.variant))
    (local $tmp7 (ref null $trait0))
    (local.set $l2 (block (result anyref)
      (local.set $tmp0 (struct.new $trait0 (local.get $l1) (struct.get $trait0 $trait0bounds (local.get $bound0)) (struct.get $trait0 $trait0m0 (local.get $bound0)) (struct.get $trait0 $trait0m1 (local.get $bound0))))
      (call_ref $tsig0_1
      (struct.get $trait0 $trait0value (local.get $tmp0))
      (local.get $tmp0)
      (struct.get $trait0 $trait0m1 (local.get $tmp0)))
    ))
    (block $break0
      (local.set $tmp1 (block (result (ref null $hd.iterator))
      (local.set $tmp4 (local.get $l0))
      (struct.new $hd.iterator
        (ref.as_non_null (local.get $tmp4))
        (ref.null $hd.map)
        (i32.const 0)
        (struct.get $hd.vector $hd.vector-version (ref.as_non_null (local.get $tmp4))))
    ))
      (loop $loop0
        (local.set $tmp2 (block (result (ref null $hd.variant))
          (local.set $tmp5 (local.get $tmp1))
          (if (result (ref null $hd.variant))
            (ref.is_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp5))))
            (then (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.map $hd.map-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp5))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp5))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5))) (struct.get $hd.map $hd.map-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp5))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp6
                (struct.new $hd.variant (i32.const 1) (array.new_fixed $hd.list 2 (array.get $hd.list (struct.get $hd.map $hd.map-keys (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp5))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5)))) (array.get $hd.list (struct.get $hd.map $hd.map-values (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp5))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5)))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5))) (i32.const 1)))
              (local.get $tmp6)))
        ))
            (else (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.vector $hd.vector-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp5))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp5))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5))) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp5))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp6
                (struct.new $hd.variant (i32.const 1) (call $hd.vector_get (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp5)))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp5))) (i32.const 1)))
              (local.get $tmp6)))
        )))
        ))
        (br_if $break0 (i32.eqz (struct.get $hd.variant $hd.variant-tag (ref.as_non_null (local.get $tmp2)))))
        (local.set $tmp3 (struct.get $hd.variant $hd.variant-payload (ref.as_non_null (local.get $tmp2))))
        (local.set $l3 (local.get $tmp3))
        (block $continue0
          (local.set $l2 (block (result anyref)
            (local.set $tmp7 (struct.new $trait0 (local.get $l2) (struct.get $trait0 $trait0bounds (local.get $bound0)) (struct.get $trait0 $trait0m0 (local.get $bound0)) (struct.get $trait0 $trait0m1 (local.get $bound0))))
            (call_ref $tsig0_0
            (struct.get $trait0 $trait0value (local.get $tmp7))
            (local.get $tmp7)
            (local.get $l3)
            (struct.get $trait0 $trait0m0 (local.get $tmp7)))
          ))
        )
        (br $loop0)
      )
    )
    (local.get $l2)
  )

(func $f1 (param $l0 (ref null $hd.vector)) (result i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $tmp0 (ref null $hd.iterator))
    (local $tmp1 (ref null $hd.variant))
    (local $tmp2 i32)
    (local $tmp3 (ref null $hd.vector))
    (local $tmp4 (ref null $hd.iterator))
    (local $tmp5 (ref null $hd.variant))
    (local.set $l1 (i32.const 0))
    (block $break1
      (local.set $tmp0 (block (result (ref null $hd.iterator))
      (local.set $tmp3 (local.get $l0))
      (struct.new $hd.iterator
        (ref.as_non_null (local.get $tmp3))
        (ref.null $hd.map)
        (i32.const 0)
        (struct.get $hd.vector $hd.vector-version (ref.as_non_null (local.get $tmp3))))
    ))
      (loop $loop1
        (local.set $tmp1 (block (result (ref null $hd.variant))
          (local.set $tmp4 (local.get $tmp0))
          (if (result (ref null $hd.variant))
            (ref.is_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))
            (then (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.map $hd.map-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp4))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (struct.get $hd.map $hd.map-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp5
                (struct.new $hd.variant (i32.const 1) (array.new_fixed $hd.list 2 (array.get $hd.list (struct.get $hd.map $hd.map-keys (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4)))) (array.get $hd.list (struct.get $hd.map $hd.map-values (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4)))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (i32.const 1)))
              (local.get $tmp5)))
        ))
            (else (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.vector $hd.vector-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp4))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp5
                (struct.new $hd.variant (i32.const 1) (call $hd.vector_get (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4)))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (i32.const 1)))
              (local.get $tmp5)))
        )))
        ))
        (br_if $break1 (i32.eqz (struct.get $hd.variant $hd.variant-tag (ref.as_non_null (local.get $tmp1)))))
        (local.set $tmp2 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (struct.get $hd.variant $hd.variant-payload (ref.as_non_null (local.get $tmp1))))))
        (local.set $l2 (local.get $tmp2))
        (block $continue1
          (local.set $l1 (call $hd.add_i32 (local.get $l1) (local.get $l2)))
        )
        (br $loop1)
      )
    )
    (local.get $l1)
  )

(func $fv1 (type $sig0) (param $env anyref) (param $l0 (ref null $hd.vector)) (result i32)
    (call $f1 (local.get $l0))
  )

(func $f2 (param $l0 (ref null $hd.vector)) (result f64)
    (local $l1 f64)
    (local $l2 f64)
    (local $tmp0 (ref null $hd.iterator))
    (local $tmp1 (ref null $hd.variant))
    (local $tmp2 f64)
    (local $tmp3 (ref null $hd.vector))
    (local $tmp4 (ref null $hd.iterator))
    (local $tmp5 (ref null $hd.variant))
    (local.set $l1 (f64.const 0))
    (block $break2
      (local.set $tmp0 (block (result (ref null $hd.iterator))
      (local.set $tmp3 (local.get $l0))
      (struct.new $hd.iterator
        (ref.as_non_null (local.get $tmp3))
        (ref.null $hd.map)
        (i32.const 0)
        (struct.get $hd.vector $hd.vector-version (ref.as_non_null (local.get $tmp3))))
    ))
      (loop $loop2
        (local.set $tmp1 (block (result (ref null $hd.variant))
          (local.set $tmp4 (local.get $tmp0))
          (if (result (ref null $hd.variant))
            (ref.is_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))
            (then (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.map $hd.map-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp4))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (struct.get $hd.map $hd.map-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp5
                (struct.new $hd.variant (i32.const 1) (array.new_fixed $hd.list 2 (array.get $hd.list (struct.get $hd.map $hd.map-keys (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4)))) (array.get $hd.list (struct.get $hd.map $hd.map-values (ref.as_non_null (struct.get $hd.iterator $hd.iterator-map (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4)))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (i32.const 1)))
              (local.get $tmp5)))
        ))
            (else (block (result (ref null $hd.variant))
          (if
            (i32.ne (struct.get $hd.vector $hd.vector-version (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))) (struct.get $hd.iterator $hd.iterator-version (ref.as_non_null (local.get $tmp4))))
            (then (call $hd.panic (i32.const 8)) unreachable))
          (if (result (ref null $hd.variant))
            (i32.ge_u (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4))))))
            (then (struct.new $hd.variant (i32.const 0) (ref.null any)))
            (else
              (local.set $tmp5
                (struct.new $hd.variant (i32.const 1) (call $hd.vector_get (ref.as_non_null (struct.get $hd.iterator $hd.iterator-list (ref.as_non_null (local.get $tmp4)))) (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))))))
              (struct.set $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))
                (i32.add (struct.get $hd.iterator $hd.iterator-index (ref.as_non_null (local.get $tmp4))) (i32.const 1)))
              (local.get $tmp5)))
        )))
        ))
        (br_if $break2 (i32.eqz (struct.get $hd.variant $hd.variant-tag (ref.as_non_null (local.get $tmp1)))))
        (local.set $tmp2 (struct.get $hd.box-f64 $hd.box-f64-value (ref.cast (ref $hd.box-f64) (struct.get $hd.variant $hd.variant-payload (ref.as_non_null (local.get $tmp1))))))
        (local.set $l2 (local.get $tmp2))
        (block $continue2
          (local.set $l1 (f64.add (local.get $l1) (local.get $l2)))
        )
        (br $loop2)
      )
    )
    (local.get $l1)
  )

(func $fv2 (type $sig1) (param $env anyref) (param $l0 (ref null $hd.vector)) (result f64)
    (call $f2 (local.get $l0))
  )

(func $f3 (param $l0 (ref null $hd.vector)) (param $bound0 (ref null $trait1)) (result i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 anyref)
    (local $tmp0 i32)
    (local $tmp1 (ref null $trait1))
    (local $tmp2 i32)
    (local.set $l1 (i32.const 1))
    (block $break3
      (loop $loop3
        (br_if $break3 (i32.eqz (block (result i32) (local.set $tmp2 (if (result i32) (i32.lt_s (local.get $l1) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (local.get $l0)))) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l1) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (local.get $l0)))) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp2) (i32.const -1)))))
        (local.set $l2 (local.get $l1))
        (block $break4
          (loop $loop4
            (br_if $break4 (i32.eqz (if (result i32) (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l2) (i32.const 0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (i32.const 0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const 1))) (then (block (result i32)
          (local.set $tmp1 (struct.new $trait1 (call $hd.vector_get (ref.as_non_null (local.get $l0)) (local.get $l2)) (struct.get $trait1 $trait1bounds (local.get $bound0)) (struct.get $trait1 $trait1m0 (local.get $bound0))))
          (call_ref $tsig1_0
          (struct.get $trait1 $trait1value (local.get $tmp1))
          (local.get $tmp1)
          (call $hd.vector_get (ref.as_non_null (local.get $l0)) (call $hd.sub_i32 (local.get $l2) (i32.const 1)))
          (struct.get $trait1 $trait1m0 (local.get $tmp1)))
        )) (else (i32.const 0)))))
            (local.set $l3 (call $hd.vector_get (ref.as_non_null (local.get $l0)) (local.get $l2)))
            (call $hd.vector_set (ref.as_non_null (local.get $l0)) (local.get $l2) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (call $hd.sub_i32 (local.get $l2) (i32.const 1))))
            (call $hd.vector_set (ref.as_non_null (local.get $l0)) (call $hd.sub_i32 (local.get $l2) (i32.const 1)) (local.get $l3))
            (local.set $l2 (call $hd.sub_i32 (local.get $l2) (i32.const 1)))
            (br $loop4)
          )
        )
        (local.set $l1 (call $hd.add_i32 (local.get $l1) (i32.const 1)))
        (br $loop3)
      )
    )
    (struct.get $hd.vector $hd.vector-size (ref.as_non_null (local.get $l0)))
  )

(func $f4 (param $l0 (ref null $hd.vector)) (result i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 i32)
    (local $tmp1 i32)
    (local $tmp2 i32)
    (local.set $l1 (i32.const 1))
    (block $break5
      (loop $loop5
        (br_if $break5 (i32.eqz (block (result i32) (local.set $tmp2 (if (result i32) (i32.lt_s (local.get $l1) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (local.get $l0)))) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l1) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (local.get $l0)))) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp2) (i32.const -1)))))
        (local.set $l2 (local.get $l1))
        (block $break6
          (loop $loop6
            (br_if $break6 (i32.eqz (if (result i32) (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l2) (i32.const 0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (i32.const 0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const 1))) (then (block (result i32) (local.set $tmp1 (if (result i32) (i32.lt_s (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (local.get $l2)))) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (call $hd.sub_i32 (local.get $l2) (i32.const 1)))))) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (local.get $l2)))) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (call $hd.sub_i32 (local.get $l2) (i32.const 1)))))) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp1) (i32.const -1)))) (else (i32.const 0)))))
            (local.set $l3 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (local.get $l2)))))
            (call $hd.vector_set (ref.as_non_null (local.get $l0)) (local.get $l2) (struct.new $hd.box-i32 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (call $hd.sub_i32 (local.get $l2) (i32.const 1)))))))
            (call $hd.vector_set (ref.as_non_null (local.get $l0)) (call $hd.sub_i32 (local.get $l2) (i32.const 1)) (struct.new $hd.box-i32 (local.get $l3)))
            (local.set $l2 (call $hd.sub_i32 (local.get $l2) (i32.const 1)))
            (br $loop6)
          )
        )
        (local.set $l1 (call $hd.add_i32 (local.get $l1) (i32.const 1)))
        (br $loop5)
      )
    )
    (call $hd.sub_i32 (call $hd.add_i32 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (i32.const 0)))) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (local.get $l0)))) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.vector_get (ref.as_non_null (local.get $l0)) (i32.const 0)))))
  )

(func $fv4 (type $sig2) (param $env anyref) (param $l0 (ref null $hd.vector)) (result i32)
    (call $f4 (local.get $l0))
  )

(func $f5 (param $l0 i32) (result (ref null $hd.vector))
    (local $l1 (ref null $hd.vector))
    (local $l2 i32)
    (local $tmp0 i32)
    (local $tmp1 i32)
    (local $tmp2 i32)
    (local.set $l1 (struct.new $hd.vector (i32.const 0) (array.new_default $hd.list (i32.const 0)) (i32.const 0)))
    (local.set $l2 (i32.const 0))
    (block $break7
      (loop $loop7
        (br_if $break7 (i32.eqz (block (result i32) (local.set $tmp2 (if (result i32) (i32.lt_s (local.get $l2) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp2) (i32.const -1)))))
        (call $hd.vector_append (ref.as_non_null (local.get $l1)) (struct.new $hd.box-i32 (block (result i32)
          (local.set $tmp0 (call $hd.mul_i32 (local.get $l2) (i32.const 7919)))
          (local.set $tmp1 (i32.const 1000))
          (if (i32.eqz (local.get $tmp1))
            (then (call $hd.panic (i32.const 1)) unreachable))
          (i32.rem_s (local.get $tmp0) (local.get $tmp1))
        )))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (i32.const 1)))
        (br $loop7)
      )
    )
    (local.get $l1)
  )

(func $fv5 (type $sig3) (param $env anyref) (param $l0 i32) (result (ref null $hd.vector))
    (call $f5 (local.get $l0))
  )

(func $f6 (param $l0 i32) (result (ref null $hd.vector))
    (local $l1 (ref null $hd.vector))
    (local $l2 i32)
    (local $l3 f64)
    (local $tmp0 i32)
    (local.set $l1 (struct.new $hd.vector (i32.const 0) (array.new_default $hd.list (i32.const 0)) (i32.const 0)))
    (local.set $l2 (i32.const 0))
    (local.set $l3 (f64.const 0.5))
    (block $break8
      (loop $loop8
        (br_if $break8 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l2) (local.get $l0)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l2) (local.get $l0)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (call $hd.vector_append (ref.as_non_null (local.get $l1)) (struct.new $hd.box-f64 (local.get $l3)))
        (local.set $l3 (f64.add (local.get $l3) (f64.const 1)))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (i32.const 1)))
        (br $loop8)
      )
    )
    (local.get $l1)
  )

(func $fv6 (type $sig4) (param $env anyref) (param $l0 i32) (result (ref null $hd.vector))
    (call $f6 (local.get $l0))
  )

(func $f7 (export "bench_sum_generic_i32") (param $l0 i32) (param $l1 i32) (result i32)
    (local $l2 (ref null $hd.vector))
    (local $l3 i32)
    (local $l4 i32)
    (local $tmp0 i32)
    (local $tmp1 i32)
    (local $tmp2 i32)
    (local.set $l2 (call $f5 (local.get $l0)))
    (local.set $l3 (i32.const 0))
    (local.set $l4 (i32.const 0))
    (block $break9
      (loop $loop9
        (br_if $break9 (i32.eqz (block (result i32) (local.set $tmp2 (if (result i32) (i32.lt_s (local.get $l4) (local.get $l1)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l4) (local.get $l1)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp2) (i32.const -1)))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (block (result i32)
          (local.set $tmp0 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $f0 (local.get $l2) (struct.new $hd.box-i32 (i32.const 0)) (struct.new $trait0 (ref.null any) (ref.null $hd.list) (ref.func $tadapt0_0) (ref.func $tadapt0_1))))))
          (local.set $tmp1 (i32.const 7))
          (if (i32.eqz (local.get $tmp1))
            (then (call $hd.panic (i32.const 1)) unreachable))
          (i32.rem_s (local.get $tmp0) (local.get $tmp1))
        )))
        (local.set $l4 (call $hd.add_i32 (local.get $l4) (i32.const 1)))
        (br $loop9)
      )
    )
    (local.get $l3)
  )

(func $fv7 (type $sig5) (param $env anyref) (param $l0 i32) (param $l1 i32) (result i32)
    (call $f7 (local.get $l0) (local.get $l1))
  )

(func $f8 (export "bench_sum_mono_i32") (param $l0 i32) (param $l1 i32) (result i32)
    (local $l2 (ref null $hd.vector))
    (local $l3 i32)
    (local $l4 i32)
    (local $tmp0 i32)
    (local $tmp1 i32)
    (local $tmp2 i32)
    (local.set $l2 (call $f5 (local.get $l0)))
    (local.set $l3 (i32.const 0))
    (local.set $l4 (i32.const 0))
    (block $break10
      (loop $loop10
        (br_if $break10 (i32.eqz (block (result i32) (local.set $tmp2 (if (result i32) (i32.lt_s (local.get $l4) (local.get $l1)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l4) (local.get $l1)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp2) (i32.const -1)))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (block (result i32)
          (local.set $tmp0 (call $f1 (local.get $l2)))
          (local.set $tmp1 (i32.const 7))
          (if (i32.eqz (local.get $tmp1))
            (then (call $hd.panic (i32.const 1)) unreachable))
          (i32.rem_s (local.get $tmp0) (local.get $tmp1))
        )))
        (local.set $l4 (call $hd.add_i32 (local.get $l4) (i32.const 1)))
        (br $loop10)
      )
    )
    (local.get $l3)
  )

(func $fv8 (type $sig5) (param $env anyref) (param $l0 i32) (param $l1 i32) (result i32)
    (call $f8 (local.get $l0) (local.get $l1))
  )

(func $f9 (export "bench_sum_generic_f64") (param $l0 i32) (param $l1 i32) (result f64)
    (local $l2 (ref null $hd.vector))
    (local $l3 f64)
    (local $l4 i32)
    (local $tmp0 i32)
    (local.set $l2 (call $f6 (local.get $l0)))
    (local.set $l3 (f64.const 0))
    (local.set $l4 (i32.const 0))
    (block $break11
      (loop $loop11
        (br_if $break11 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l4) (local.get $l1)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l4) (local.get $l1)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l3 (f64.add (local.get $l3) (struct.get $hd.box-f64 $hd.box-f64-value (ref.cast (ref $hd.box-f64) (call $f0 (local.get $l2) (struct.new $hd.box-f64 (f64.const 0)) (struct.new $trait0 (ref.null any) (ref.null $hd.list) (ref.func $tadapt1_0) (ref.func $tadapt1_1)))))))
        (local.set $l4 (call $hd.add_i32 (local.get $l4) (i32.const 1)))
        (br $loop11)
      )
    )
    (local.get $l3)
  )

(func $fv9 (type $sig6) (param $env anyref) (param $l0 i32) (param $l1 i32) (result f64)
    (call $f9 (local.get $l0) (local.get $l1))
  )

(func $f10 (export "bench_sum_mono_f64") (param $l0 i32) (param $l1 i32) (result f64)
    (local $l2 (ref null $hd.vector))
    (local $l3 f64)
    (local $l4 i32)
    (local $tmp0 i32)
    (local.set $l2 (call $f6 (local.get $l0)))
    (local.set $l3 (f64.const 0))
    (local.set $l4 (i32.const 0))
    (block $break12
      (loop $loop12
        (br_if $break12 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l4) (local.get $l1)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l4) (local.get $l1)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l3 (f64.add (local.get $l3) (call $f2 (local.get $l2))))
        (local.set $l4 (call $hd.add_i32 (local.get $l4) (i32.const 1)))
        (br $loop12)
      )
    )
    (local.get $l3)
  )

(func $fv10 (type $sig6) (param $env anyref) (param $l0 i32) (param $l1 i32) (result f64)
    (call $f10 (local.get $l0) (local.get $l1))
  )

(func $f11 (export "bench_sort_generic_i32") (param $l0 i32) (param $l1 i32) (result i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 i32)
    (local.set $l2 (i32.const 0))
    (local.set $l3 (i32.const 0))
    (block $break13
      (loop $loop13
        (br_if $break13 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l3) (local.get $l1)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l3) (local.get $l1)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (call $f3 (call $f5 (local.get $l0)) (struct.new $trait1 (ref.null any) (ref.null $hd.list) (ref.func $tadapt2_0)))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (i32.const 1)))
        (br $loop13)
      )
    )
    (local.get $l2)
  )

(func $fv11 (type $sig5) (param $env anyref) (param $l0 i32) (param $l1 i32) (result i32)
    (call $f11 (local.get $l0) (local.get $l1))
  )

(func $f12 (export "bench_sort_mono_i32") (param $l0 i32) (param $l1 i32) (result i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 i32)
    (local.set $l2 (i32.const 0))
    (local.set $l3 (i32.const 0))
    (block $break14
      (loop $loop14
        (br_if $break14 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l3) (local.get $l1)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l3) (local.get $l1)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (call $f4 (call $f5 (local.get $l0)))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (i32.const 1)))
        (br $loop14)
      )
    )
    (local.get $l2)
  )

(func $fv12 (type $sig5) (param $env anyref) (param $l0 i32) (param $l1 i32) (result i32)
    (call $f12 (local.get $l0) (local.get $l1))
  )

(func $f13 (export "bench_build_i32") (param $l0 i32) (param $l1 i32) (result i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $tmp0 i32)
    (local.set $l2 (i32.const 0))
    (local.set $l3 (i32.const 0))
    (block $break15
      (loop $loop15
        (br_if $break15 (i32.eqz (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l3) (local.get $l1)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l3) (local.get $l1)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))))
        (local.set $l2 (call $hd.add_i32 (local.get $l2) (struct.get $hd.vector $hd.vector-size (ref.as_non_null (call $f5 (local.get $l0))))))
        (local.set $l3 (call $hd.add_i32 (local.get $l3) (i32.const 1)))
        (br $loop15)
      )
    )
    (local.get $l2)
  )

(func $fv13 (type $sig5) (param $env anyref) (param $l0 i32) (param $l1 i32) (result i32)
    (call $f13 (local.get $l0) (local.get $l1))
  )

(func $f14 (export "main") (result i32)
    (call $hd.sub_i32 (call $hd.add_i32 (call $hd.sub_i32 (call $f7 (i32.const 10) (i32.const 1)) (call $f8 (i32.const 10) (i32.const 1))) (call $f11 (i32.const 10) (i32.const 1))) (call $f12 (i32.const 10) (i32.const 1)))
  )

(func $fv14 (type $sig7) (param $env anyref)  (result i32)
    (call $f14)
  )

(func $f15 (param $l0 i32) (param $l1 i32) (result i32)
    (call $hd.add_i32 (local.get $l0) (local.get $l1))
  )

(func $fv15 (type $sig5) (param $env anyref) (param $l0 i32) (param $l1 i32) (result i32)
    (call $f15 (local.get $l0) (local.get $l1))
  )

(func $f16 (param $l0 i32) (result i32)
    (i32.const 0)
  )

(func $fv16 (type $sig8) (param $env anyref) (param $l0 i32) (result i32)
    (call $f16 (local.get $l0))
  )

(func $f17 (param $l0 f64) (param $l1 f64) (result f64)
    (f64.add (local.get $l0) (local.get $l1))
  )

(func $fv17 (type $sig9) (param $env anyref) (param $l0 f64) (param $l1 f64) (result f64)
    (call $f17 (local.get $l0) (local.get $l1))
  )

(func $f18 (param $l0 f64) (result f64)
    (f64.const 0)
  )

(func $fv18 (type $sig10) (param $env anyref) (param $l0 f64) (result f64)
    (call $f18 (local.get $l0))
  )

(func $f19 (param $l0 i32) (param $l1 i32) (result i32)
    (local $tmp0 i32)
    (block (result i32) (local.set $tmp0 (if (result i32) (i32.lt_s (local.get $l0) (local.get $l1)) (then (i32.const -1)) (else (if (result i32) (i32.gt_s (local.get $l0) (local.get $l1)) (then (i32.const 1)) (else (i32.const 0)))))) (i32.eq (local.get $tmp0) (i32.const -1)))
  )

(func $fv19 (type $sig11) (param $env anyref) (param $l0 i32) (param $l1 i32) (result i32)
    (call $f19 (local.get $l0) (local.get $l1))
  )

(func $tadapt0_0 (type $tsig0_0) (param $self anyref) (param $dictionary anyref) (param $a0 anyref) (result anyref)
    (struct.new $hd.box-i32 (call $f15 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (local.get $self))) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (local.get $a0)))))
  )

(func $tadapt0_1 (type $tsig0_1) (param $self anyref) (param $dictionary anyref)  (result anyref)
    (struct.new $hd.box-i32 (call $f16 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (local.get $self)))))
  )

(func $tadapt1_0 (type $tsig0_0) (param $self anyref) (param $dictionary anyref) (param $a0 anyref) (result anyref)
    (struct.new $hd.box-f64 (call $f17 (struct.get $hd.box-f64 $hd.box-f64-value (ref.cast (ref $hd.box-f64) (local.get $self))) (struct.get $hd.box-f64 $hd.box-f64-value (ref.cast (ref $hd.box-f64) (local.get $a0)))))
  )

(func $tadapt1_1 (type $tsig0_1) (param $self anyref) (param $dictionary anyref)  (result anyref)
    (struct.new $hd.box-f64 (call $f18 (struct.get $hd.box-f64 $hd.box-f64-value (ref.cast (ref $hd.box-f64) (local.get $self)))))
  )

(func $tadapt2_0 (type $tsig1_0) (param $self anyref) (param $dictionary anyref) (param $a0 anyref) (result i32)
    (call $f19 (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (local.get $self))) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (local.get $a0))))
  )
