;; commit bd985d7; command: om-build.ts (emitWat of audit/probes/arch/object-model/om-suspend.hd); date: 2026-09-25T20:54:06.500Z
;; excerpt: rec types, user globals, user functions (runtime $hd.* functions omitted)
(rec
    (type $sig0 (func (param anyref) (param i32) (result (ref null $hd.suspension))))
    (type $sig1 (func (param anyref) (result (ref null $hd.suspension))))
    (type $tsig0_0 (func (param anyref) (param anyref) (result (ref null $hd.bytes))))
    (type $tsig1_0 (func (param anyref) (param anyref) (param anyref) (result i32)))
    (type $tsig2_0 (func (param anyref) (param anyref) (param anyref) (result (ref null $hd.variant))))
    (type $tsig3_0 (func (param anyref) (param anyref)))
    (type $tsig4_0 (func (param anyref) (param anyref) (result (ref null $hd.variant))))
    (type $hd.suspension-poll-sig (func (param anyref) (result i32)))
    (type $hd.suspension-cancel-sig (func (param anyref)))
    (type $hd.suspension-result-sig (func (param anyref) (result anyref)))
    (type $hd.suspension (struct
      (field $hd.suspension-inner anyref)
      (field $hd.suspension-poll (ref $hd.suspension-poll-sig))
      (field $hd.suspension-cancel (ref $hd.suspension-cancel-sig))
      (field $hd.suspension-result (ref $hd.suspension-result-sig))))
    (type $hd.bytes (array (mut i8)))
    (type $hd.list (array (mut anyref)))
    (type $hd.vector (struct
      (field $hd.vector-size (mut i32))
      (field $hd.vector-values (mut (ref $hd.list)))
      (field $hd.vector-version (mut i32))))
    (type $hd.iterator (struct
      (field $hd.iterator-list (ref null $hd.vector))
      (field $hd.iterator-map (ref null $hd.map))
      (field $hd.iterator-index (mut i32))
      (field $hd.iterator-version i32)))
    (type $hd.map (struct
      (field $hd.map-key-kind i32)
      (field $hd.map-size (mut i32))
      (field $hd.map-keys (mut (ref $hd.list)))
      (field $hd.map-values (mut (ref $hd.list)))
      (field $hd.map-version (mut i32))))
    (type $hd.providers (struct
      (field $hd.provider-key i32)
      (field $hd.provider-value anyref)
      (field $hd.provider-parent (ref null $hd.providers))))
    (type $hd.box-i32 (struct
      (field $hd.box-i32-value i32)))
    (type $hd.box-f64 (struct
      (field $hd.box-f64-value f64)))
    (type $hd.box-extern (struct
      (field $hd.box-extern-value externref)))
    (type $hd.variant (struct
      (field $hd.variant-tag i32)
      (field $hd.variant-payload (mut anyref))))
    (type $closure0 (struct
      (field $closure0fn (ref $sig0))
      (field $closure0env anyref)))
    (type $closure1 (struct
      (field $closure1fn (ref $sig1))
      (field $closure1env anyref)))
    (type $trait0 (struct
      (field $trait0value anyref)
      (field $trait0bounds (ref null $hd.list))
      (field $trait0m0 (ref $tsig0_0))))
    (type $trait1 (struct
      (field $trait1value anyref)
      (field $trait1bounds (ref null $hd.list))
      (field $trait1m0 (ref $tsig1_0))))
    (type $trait2 (struct
      (field $trait2value anyref)
      (field $trait2bounds (ref null $hd.list))
      (field $trait2m0 (ref $tsig2_0))))
    (type $trait3 (struct
      (field $trait3value anyref)
      (field $trait3bounds (ref null $hd.list))
      (field $trait3m0 (ref $tsig3_0))))
    (type $trait4 (struct
      (field $trait4value anyref)
      (field $trait4bounds (ref null $hd.list))
      (field $trait4m0 (ref $tsig4_0))))
    (type $s0 (struct
      (field $s0state (mut i32))
      (field $s0polls (mut i32))
      (field $s0a0 i32)
      (field $s0result (mut i32))))
    (type $s1 (struct
      (field $s1state (mut i32))
      (field $s1polls (mut i32))
      (field $s1a0 i32)
      (field $s1l1 (mut (ref null $hd.suspension)))
      (field $s1child0 (mut (ref null $hd.suspension)))
      (field $s1result (mut i32))))
    (type $s2 (struct
      (field $s2state (mut i32))
      (field $s2polls (mut i32))
      (field $s2a0 i32)
      (field $s2child0 (mut (ref null $s0)))
      (field $s2result (mut i32))))
    (type $s3 (struct
      (field $s3state (mut i32))
      (field $s3polls (mut i32))
      (field $s3l0 (mut i32))
      (field $s3l1 (mut i32))
      (field $s3l2 (mut i32))
      (field $s3l3 (mut i32))
      (field $s3l4 (mut i32))
      (field $s3l5 (mut i32))
      (field $s3l6 (mut i32))
      (field $s3child0 (mut (ref null $s2)))
      (field $s3child1 (mut (ref null $s1)))
      (field $s3result (mut i32))))
    (type $e0 (struct
      (field $e0tag i32)))
    (type $hd.runtime (struct
      (field $status (mut i32))
      (field $scratch (mut (ref null $hd.bytes)))))
  )

(global $e0v0 (ref $e0)
    (struct.new $e0 (i32.const 0)))

(global $e0v1 (ref $e0)
    (struct.new $e0 (i32.const 1)))

(global $e0v2 (ref $e0)
    (struct.new $e0 (i32.const 2)))

(func $body0 (param $l0 i32) (result i32)
    (call $hd.add_i32 (local.get $l0) (i32.const 1))
  )

(func $f0 (param $l0 i32) (result (ref null $s0))
    (call $hd.trace (i32.const 0) (i32.const 0))
    (struct.new $s0 (i32.const 0) (i32.const 0) (local.get $l0) (i32.const 0))
  )

(func $poll0 (param $frame (ref null $s0)) (result i32)
    (call $hd.trace (i32.const 0) (i32.const 1))
    (if (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 1))
      (then (call $hd.trace (i32.const 0) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or
          (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 2))
          (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 3)))
      (then (call $hd.trace (i32.const 0) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s0 $s0polls (local.get $frame)
      (i32.add (struct.get $s0 $s0polls (local.get $frame)) (i32.const 1)))
    (struct.set $s0 $s0state (local.get $frame) (i32.const 1))
    (if (call $hd.pending
          (i32.const 0)
          (struct.get $s0 $s0polls (local.get $frame)))
      (then
        (struct.set $s0 $s0state (local.get $frame) (i32.const 4))
        (call $hd.trace (i32.const 0) (i32.const 6))
        (return (i32.const 0))))
    (struct.set $s0 $s0state (local.get $frame) (i32.const 1))
    (struct.set $s0 $s0result (local.get $frame) (call $body0 (struct.get $s0 $s0a0 (local.get $frame))))
    (struct.set $s0 $s0state (local.get $frame) (i32.const 2))
    (call $hd.trace (i32.const 0) (i32.const 2))
    (i32.const 1)
  )

(func $drive0 (param $frame (ref null $s0)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll0 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s0 $s0result (local.get $frame))
  )

(func $cancel0 (param $frame (ref null $s0))
    (call $hd.trace (i32.const 0) (i32.const 3))
    (if (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 1))
      (then (call $hd.trace (i32.const 0) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or
          (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 0))
          (i32.eq (struct.get $s0 $s0state (local.get $frame)) (i32.const 4)))
      (then (struct.set $s0 $s0state (local.get $frame) (i32.const 3))))
  )

(func $fv0 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f0 (local.get $l0)) (ref.func $swpoll0) (ref.func $swcancel0) (ref.func $swresult0))
  )

(func $f1 (param $l0 i32) (result (ref null $s1))
    (call $hd.trace (i32.const 1) (i32.const 0))
    (struct.new $s1 (i32.const 0) (i32.const 0) (local.get $l0) (ref.null $hd.suspension) (ref.null $hd.suspension) (i32.const 0))
  )

(func $poll1 (param $frame (ref null $s1)) (result i32)
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 (ref null $hd.suspension))
    (call $hd.trace (i32.const 1) (i32.const 1))
    (local.set $resume-state (struct.get $s1 $s1state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 1) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 2)) (i32.eq (local.get $resume-state) (i32.const 3)))
      (then (call $hd.trace (i32.const 1) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s1 $s1polls (local.get $frame)
      (i32.add (struct.get $s1 $s1polls (local.get $frame)) (i32.const 1)))
    (struct.set $s1 $s1state (local.get $frame) (i32.const 1))
    (if (call $hd.pending (i32.const 1) (struct.get $s1 $s1polls (local.get $frame)))
      (then
        (struct.set $s1 $s1state (local.get $frame)
          (if (result i32) (i32.eq (local.get $resume-state) (i32.const 0))
            (then (i32.const 4))
            (else (local.get $resume-state))))
        (call $hd.trace (i32.const 1) (i32.const 6))
        (return (i32.const 0))))
    (local.set $l0 (struct.get $s1 $s1a0 (local.get $frame)))
    (local.set $l1 (struct.get $s1 $s1l1 (local.get $frame)))
    (struct.set $s1 $s1state (local.get $frame) (i32.const 1))
    (if (i32.le_u (local.get $resume-state) (i32.const 4))
      (then
        (local.set $l1 (struct.new $hd.suspension (call $f0 (local.get $l0)) (ref.func $swpoll0) (ref.func $swcancel0) (ref.func $swresult0)))
        (struct.set $s1 $s1child0 (local.get $frame) (local.get $l1))
        (if (i32.eqz (call $hd.suspension_poll (struct.get $s1 $s1child0 (local.get $frame))))
          (then
            (struct.set $s1 $s1l1 (local.get $frame) (local.get $l1))
            (struct.set $s1 $s1state (local.get $frame) (i32.const 5))
            (call $hd.trace (i32.const 1) (i32.const 6))
            (return (i32.const 0))))
        (struct.set $s1 $s1result (local.get $frame) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.suspension_result (struct.get $s1 $s1child0 (local.get $frame))))))
        (struct.set $s1 $s1state (local.get $frame) (i32.const 2))
        (call $hd.trace (i32.const 1) (i32.const 2))
        (return (i32.const 1))
      )
      (else
        (if (i32.eq (local.get $resume-state) (i32.const 5))
          (then
            (if (i32.eqz (call $hd.suspension_poll (struct.get $s1 $s1child0 (local.get $frame))))
              (then
                (struct.set $s1 $s1l1 (local.get $frame) (local.get $l1))
                (struct.set $s1 $s1state (local.get $frame) (i32.const 5))
                (call $hd.trace (i32.const 1) (i32.const 6))
                (return (i32.const 0))))
            (struct.set $s1 $s1result (local.get $frame) (struct.get $hd.box-i32 $hd.box-i32-value (ref.cast (ref $hd.box-i32) (call $hd.suspension_result (struct.get $s1 $s1child0 (local.get $frame))))))
            (struct.set $s1 $s1state (local.get $frame) (i32.const 2))
            (call $hd.trace (i32.const 1) (i32.const 2))
            (return (i32.const 1))
          )
          (else
            (unreachable)
          ))
      ))
  )

(func $drive1 (param $frame (ref null $s1)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll1 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s1 $s1result (local.get $frame))
  )

(func $cancel1 (param $frame (ref null $s1))
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 (ref null $hd.suspension))
    (call $hd.trace (i32.const 1) (i32.const 3))
    (local.set $resume-state (struct.get $s1 $s1state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 1) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (local.set $l0 (struct.get $s1 $s1a0 (local.get $frame)))
    (local.set $l1 (struct.get $s1 $s1l1 (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 5))
      (then
        (call $hd.suspension_cancel (struct.get $s1 $s1child0 (local.get $frame)))
        (struct.set $s1 $s1state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 0)) (i32.eq (local.get $resume-state) (i32.const 4)))
      (then (struct.set $s1 $s1state (local.get $frame) (i32.const 3))))
  )

(func $fv1 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f1 (local.get $l0)) (ref.func $swpoll1) (ref.func $swcancel1) (ref.func $swresult1))
  )

(func $f2 (param $l0 i32) (result (ref null $s2))
    (call $hd.trace (i32.const 2) (i32.const 0))
    (struct.new $s2 (i32.const 0) (i32.const 0) (local.get $l0) (ref.null $s0) (i32.const 0))
  )

(func $poll2 (param $frame (ref null $s2)) (result i32)
    (local $resume-state i32)
    (local $l0 i32)
    (call $hd.trace (i32.const 2) (i32.const 1))
    (local.set $resume-state (struct.get $s2 $s2state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 2) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 2)) (i32.eq (local.get $resume-state) (i32.const 3)))
      (then (call $hd.trace (i32.const 2) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s2 $s2polls (local.get $frame)
      (i32.add (struct.get $s2 $s2polls (local.get $frame)) (i32.const 1)))
    (struct.set $s2 $s2state (local.get $frame) (i32.const 1))
    (if (call $hd.pending (i32.const 2) (struct.get $s2 $s2polls (local.get $frame)))
      (then
        (struct.set $s2 $s2state (local.get $frame)
          (if (result i32) (i32.eq (local.get $resume-state) (i32.const 0))
            (then (i32.const 4))
            (else (local.get $resume-state))))
        (call $hd.trace (i32.const 2) (i32.const 6))
        (return (i32.const 0))))
    (local.set $l0 (struct.get $s2 $s2a0 (local.get $frame)))
    (struct.set $s2 $s2state (local.get $frame) (i32.const 1))
    (if (i32.le_u (local.get $resume-state) (i32.const 4))
      (then
        (struct.set $s2 $s2child0 (local.get $frame) (call $f0 (local.get $l0)))
        (if (i32.eqz (call $poll0 (struct.get $s2 $s2child0 (local.get $frame))))
          (then
            (struct.set $s2 $s2state (local.get $frame) (i32.const 5))
            (call $hd.trace (i32.const 2) (i32.const 6))
            (return (i32.const 0))))
        (struct.set $s2 $s2result (local.get $frame) (struct.get $s0 $s0result (struct.get $s2 $s2child0 (local.get $frame))))
        (struct.set $s2 $s2state (local.get $frame) (i32.const 2))
        (call $hd.trace (i32.const 2) (i32.const 2))
        (return (i32.const 1))
      )
      (else
        (if (i32.eq (local.get $resume-state) (i32.const 5))
          (then
            (if (i32.eqz (call $poll0 (struct.get $s2 $s2child0 (local.get $frame))))
              (then
                (struct.set $s2 $s2state (local.get $frame) (i32.const 5))
                (call $hd.trace (i32.const 2) (i32.const 6))
                (return (i32.const 0))))
            (struct.set $s2 $s2result (local.get $frame) (struct.get $s0 $s0result (struct.get $s2 $s2child0 (local.get $frame))))
            (struct.set $s2 $s2state (local.get $frame) (i32.const 2))
            (call $hd.trace (i32.const 2) (i32.const 2))
            (return (i32.const 1))
          )
          (else
            (unreachable)
          ))
      ))
  )

(func $drive2 (param $frame (ref null $s2)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll2 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s2 $s2result (local.get $frame))
  )

(func $cancel2 (param $frame (ref null $s2))
    (local $resume-state i32)
    (local $l0 i32)
    (call $hd.trace (i32.const 2) (i32.const 3))
    (local.set $resume-state (struct.get $s2 $s2state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 2) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (local.set $l0 (struct.get $s2 $s2a0 (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 5))
      (then
        (call $cancel0 (struct.get $s2 $s2child0 (local.get $frame)))
        (struct.set $s2 $s2state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 0)) (i32.eq (local.get $resume-state) (i32.const 4)))
      (then (struct.set $s2 $s2state (local.get $frame) (i32.const 3))))
  )

(func $fv2 (type $sig0) (param $env anyref) (param $l0 i32) (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f2 (local.get $l0)) (ref.func $swpoll2) (ref.func $swcancel2) (ref.func $swresult2))
  )

(func $f3 (result (ref null $s3))
    (call $hd.trace (i32.const 3) (i32.const 0))
    (struct.new $s3 (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (ref.null $s2) (ref.null $s1) (i32.const 0))
  )

(func $poll3 (param $frame (ref null $s3)) (result i32)
    (local $resume-state i32)
    (local $pc i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (local $l5 i32)
    (local $l6 i32)
    (call $hd.trace (i32.const 3) (i32.const 1))
    (local.set $resume-state (struct.get $s3 $s3state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 3) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 2)) (i32.eq (local.get $resume-state) (i32.const 3)))
      (then (call $hd.trace (i32.const 3) (i32.const 5)) (call $hd.panic (i32.const 4)) unreachable))
    (struct.set $s3 $s3polls (local.get $frame)
      (i32.add (struct.get $s3 $s3polls (local.get $frame)) (i32.const 1)))
    (struct.set $s3 $s3state (local.get $frame) (i32.const 1))
    (if (call $hd.pending (i32.const 3) (struct.get $s3 $s3polls (local.get $frame)))
      (then
        (struct.set $s3 $s3state (local.get $frame)
          (if (result i32) (i32.eq (local.get $resume-state) (i32.const 0))
            (then (i32.const 4))
            (else (local.get $resume-state))))
        (call $hd.trace (i32.const 3) (i32.const 6))
        (return (i32.const 0))))
    (local.set $l0 (struct.get $s3 $s3l0 (local.get $frame)))
    (local.set $l1 (struct.get $s3 $s3l1 (local.get $frame)))
    (local.set $l2 (struct.get $s3 $s3l2 (local.get $frame)))
    (local.set $l3 (struct.get $s3 $s3l3 (local.get $frame)))
    (local.set $l4 (struct.get $s3 $s3l4 (local.get $frame)))
    (local.set $l5 (struct.get $s3 $s3l5 (local.get $frame)))
    (local.set $l6 (struct.get $s3 $s3l6 (local.get $frame)))
    (struct.set $s3 $s3state (local.get $frame) (i32.const 1))
    (if (i32.le_u (local.get $resume-state) (i32.const 4))
      (then (local.set $pc (i32.const 6)))
      (else
        (if (i32.eq (local.get $resume-state) (i32.const 5))
          (then
            (if (i32.eqz (call $poll2 (struct.get $s3 $s3child0 (local.get $frame))))
              (then
                (struct.set $s3 $s3l0 (local.get $frame) (local.get $l0))
                (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
                (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
                (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
                (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
                (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
                (struct.set $s3 $s3l6 (local.get $frame) (local.get $l6))
                (struct.set $s3 $s3state (local.get $frame) (local.get $resume-state))
                (call $hd.trace (i32.const 3) (i32.const 6))
                (return (i32.const 0))))
            (local.set $l4 (struct.get $s2 $s2result (struct.get $s3 $s3child0 (local.get $frame))))
            (local.set $pc (i32.const 1))
          )
          (else
            (if (i32.eq (local.get $resume-state) (i32.const 6))
              (then
                (if (i32.eqz (call $poll1 (struct.get $s3 $s3child1 (local.get $frame))))
                  (then
                    (struct.set $s3 $s3l0 (local.get $frame) (local.get $l0))
                    (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
                    (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
                    (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
                    (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
                    (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
                    (struct.set $s3 $s3l6 (local.get $frame) (local.get $l6))
                    (struct.set $s3 $s3state (local.get $frame) (local.get $resume-state))
                    (call $hd.trace (i32.const 3) (i32.const 6))
                    (return (i32.const 0))))
                (local.set $l1 (struct.get $s1 $s1result (struct.get $s3 $s3child1 (local.get $frame))))
                (local.set $pc (i32.const 4))
              )
              (else
                (local.set $pc (i32.const 6))
              ))
          ))
      ))
    (loop $cfg
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (local.set $l6 (call $hd.add_i32 (local.get $l2) (local.get $l5)))
          (struct.set $s3 $s3result (local.get $frame) (local.get $l6))
          (struct.set $s3 $s3state (local.get $frame) (i32.const 2))
          (call $hd.trace (i32.const 3) (i32.const 2))
          (return (i32.const 1))
        ))
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $l5 (local.get $l4))
          (local.set $pc (i32.const 0))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (struct.set $s3 $s3child0 (local.get $frame) (call $f2 (local.get $l3)))
          (if (i32.eqz (call $poll2 (struct.get $s3 $s3child0 (local.get $frame))))
            (then
              (struct.set $s3 $s3l0 (local.get $frame) (local.get $l0))
              (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
              (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
              (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
              (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
              (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
              (struct.set $s3 $s3l6 (local.get $frame) (local.get $l6))
              (struct.set $s3 $s3state (local.get $frame) (i32.const 5))
              (call $hd.trace (i32.const 3) (i32.const 6))
              (return (i32.const 0))))
          (local.set $l4 (struct.get $s2 $s2result (struct.get $s3 $s3child0 (local.get $frame))))
          (local.set $pc (i32.const 1))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $l3 (i32.const 20))
          (local.set $pc (i32.const 2))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $l2 (local.get $l1))
          (local.set $pc (i32.const 3))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (struct.set $s3 $s3child1 (local.get $frame) (call $f1 (local.get $l0)))
          (if (i32.eqz (call $poll1 (struct.get $s3 $s3child1 (local.get $frame))))
            (then
              (struct.set $s3 $s3l0 (local.get $frame) (local.get $l0))
              (struct.set $s3 $s3l1 (local.get $frame) (local.get $l1))
              (struct.set $s3 $s3l2 (local.get $frame) (local.get $l2))
              (struct.set $s3 $s3l3 (local.get $frame) (local.get $l3))
              (struct.set $s3 $s3l4 (local.get $frame) (local.get $l4))
              (struct.set $s3 $s3l5 (local.get $frame) (local.get $l5))
              (struct.set $s3 $s3l6 (local.get $frame) (local.get $l6))
              (struct.set $s3 $s3state (local.get $frame) (i32.const 6))
              (call $hd.trace (i32.const 3) (i32.const 6))
              (return (i32.const 0))))
          (local.set $l1 (struct.get $s1 $s1result (struct.get $s3 $s3child1 (local.get $frame))))
          (local.set $pc (i32.const 4))
          (br $cfg)
        ))
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $l0 (i32.const 20))
          (local.set $pc (i32.const 5))
          (br $cfg)
        ))
      unreachable
    )
  )

(func $drive3 (param $frame (ref null $s3)) (result i32)
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (block $ready
      (loop $drive
        (br_if $ready (i32.eq (call $poll3 (local.get $frame)) (i32.const 1)))
        (br $drive)))
    (global.set $hd.driver-active (i32.const 0))
    (struct.get $s3 $s3result (local.get $frame))
  )

(func $cancel3 (param $frame (ref null $s3))
    (local $resume-state i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $l3 i32)
    (local $l4 i32)
    (local $l5 i32)
    (local $l6 i32)
    (call $hd.trace (i32.const 3) (i32.const 3))
    (local.set $resume-state (struct.get $s3 $s3state (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 1))
      (then (call $hd.trace (i32.const 3) (i32.const 4)) (call $hd.panic (i32.const 5)) unreachable))
    (local.set $l0 (struct.get $s3 $s3l0 (local.get $frame)))
    (local.set $l1 (struct.get $s3 $s3l1 (local.get $frame)))
    (local.set $l2 (struct.get $s3 $s3l2 (local.get $frame)))
    (local.set $l3 (struct.get $s3 $s3l3 (local.get $frame)))
    (local.set $l4 (struct.get $s3 $s3l4 (local.get $frame)))
    (local.set $l5 (struct.get $s3 $s3l5 (local.get $frame)))
    (local.set $l6 (struct.get $s3 $s3l6 (local.get $frame)))
    (if (i32.eq (local.get $resume-state) (i32.const 5))
      (then
        (call $cancel2 (struct.get $s3 $s3child0 (local.get $frame)))
        (struct.set $s3 $s3state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.eq (local.get $resume-state) (i32.const 6))
      (then
        (call $cancel1 (struct.get $s3 $s3child1 (local.get $frame)))
        (struct.set $s3 $s3state (local.get $frame) (i32.const 3))
        (return)))
    (if (i32.or (i32.eq (local.get $resume-state) (i32.const 0)) (i32.eq (local.get $resume-state) (i32.const 4)))
      (then (struct.set $s3 $s3state (local.get $frame) (i32.const 3))))
  )

(func $entry3 (export "main") (result i32)
    (call $drive3 (call $f3))
  )

(func (export "__hd_start")
    (if (global.get $hd.driver-active) (then (call $hd.panic (i32.const 6)) unreachable))
    (global.set $hd.driver-active (i32.const 1))
    (global.set $hd.dev-frame3 (call $f3))
  )

(func (export "__hd_poll") (result i32)
    (local $ready i32)
    (local.set $ready (call $poll3 (global.get $hd.dev-frame3)))
    (if (local.get $ready) (then (global.set $hd.driver-active (i32.const 0))))
    (local.get $ready)
  )

(func (export "__hd_cancel")
    (call $cancel3 (global.get $hd.dev-frame3))
    (global.set $hd.driver-active (i32.const 0))
  )

(func (export "__hd_result") (result i32) (struct.get $s3 $s3result (global.get $hd.dev-frame3)))

(func $fv3 (type $sig1) (param $env anyref)  (result (ref null $hd.suspension))
    (struct.new $hd.suspension (call $f3) (ref.func $swpoll3) (ref.func $swcancel3) (ref.func $swresult3))
  )

(func $swpoll0 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll0 (ref.cast (ref $s0) (local.get $inner))))

(func $swcancel0 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel0 (ref.cast (ref $s0) (local.get $inner))))

(func $swresult0 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s0 $s0result (ref.cast (ref $s0) (local.get $inner)))))

(func $swpoll1 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll1 (ref.cast (ref $s1) (local.get $inner))))

(func $swcancel1 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel1 (ref.cast (ref $s1) (local.get $inner))))

(func $swresult1 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s1 $s1result (ref.cast (ref $s1) (local.get $inner)))))

(func $swpoll2 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll2 (ref.cast (ref $s2) (local.get $inner))))

(func $swcancel2 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel2 (ref.cast (ref $s2) (local.get $inner))))

(func $swresult2 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s2 $s2result (ref.cast (ref $s2) (local.get $inner)))))

(func $swpoll3 (type $hd.suspension-poll-sig) (param $inner anyref) (result i32)
    (call $poll3 (ref.cast (ref $s3) (local.get $inner))))

(func $swcancel3 (type $hd.suspension-cancel-sig) (param $inner anyref)
    (call $cancel3 (ref.cast (ref $s3) (local.get $inner))))

(func $swresult3 (type $hd.suspension-result-sig) (param $inner anyref) (result anyref)
    (struct.new $hd.box-i32 (struct.get $s3 $s3result (ref.cast (ref $s3) (local.get $inner)))))
