// Every prelude name, which no declaration or binding may shadow
// (spec/10-modules.md#prelude).
export const PRELUDE_NAMES = new Set([
  "never",
  "bool",
  "i8",
  "i16",
  "i32",
  "i64",
  "u8",
  "u16",
  "u32",
  "u64",
  "f32",
  "f64",
  "char",
  "string",
  "void",
  "List",
  "Map",
  "Any",
  "AnyVal",
  "AnyRef",
  "Option",
  "Result",
  "panic",
  "Display",
  // std.format's Debug trait and debug function (spec/10-modules.md#prelude);
  // the prototype reserves the names but implements neither.
  "Debug",
  "debug",
  "Eq",
  "PartialOrd",
  "Ord",
  "Ordering",
  "Hash",
  "Hasher",
  "Iterator",
  "Iterable",
  "Console",
  "ConsoleError",
  "println",
  "Suspend",
  "Poll",
  "PollContext",
  "Waker",
  "ShapeMetadata",
  "DeclarationId",
  "DeclarationKind",
  "PrimitiveKind",
  "SourcePosition",
  "TypeShape",
  "DataShape",
  "FieldShape",
  "EnumShape",
  "VariantShape",
  "FnShape",
  "ParamShape",
  "shape",
  "shape_of",
  // std.testing's test-case function (spec/10-modules.md#r-module.prelude.it-function).
  "it",
]);
