[package]
name = "hd_syntax"
version = "0.0.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hd_base = { path = "../hd_base" }
hd_diag = { path = "../hd_diag" }
hd_intern = { path = "../hd_intern" }
unicode-ident = "1.0"
unicode-normalization = "0.1"

[lints]
workspace = true

