[package]
name = "hd_cli"
version = "0.0.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "hd"
path = "src/main.rs"

[dependencies]
hd_cache = { path = "../hd_cache", features = ["disk"] }
hd_check = { path = "../hd_check" }
hd_diag = { path = "../hd_diag" }
hd_driver ={ path = "../hd_driver" }
hd_fmt = { path = "../hd_fmt" }
hd_project = { path = "../hd_project" }
hd_run = { path = "../hd_run" }
hd_sched = { path = "../hd_sched", features = ["threads"] }

[lints]
workspace = true
